Main sample Scala sources ported to Java
akka/akka-platform-guide pull request #213
Opened 2020-09-25 16:40 UTC by johanandren

Work in progress on adding Java samples

2020-10-07 15:26 UTC, johanandren commented on docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-java/README.md
> +    ```
I had some issue when trying to use exec:java (run in same JVM as mvn) so ended up using exec:exec but then you have to do this little maven property dance to pass system properties to the spawned JVM.

2020-10-07 15:37 UTC, johanandren commented on docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-java/src/test/java/shopping/cart/ItemPopularityIntegrationTest.java
> +        ).withFallback(ConfigFactory.load("item-popularity-integration-test.conf"));
Since long string blocks are hard to read in Java I opted for putting everything non-dynamic in a test config file. 
Had some issues with falling back default `application.conf` (or if it was the next level of pulling in configs from there, the journal plugin ended up not being set) that I never figured out so I put an include up top in that test config rather than programatic fallback even if I would have preferred that.

2020-10-07 15:38 UTC, johanandren commented on docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-java/src/test/java/shopping/cart/IntegrationTest.java
> +        // add from client1, consume event on node3
comment seems incorrect, we are only interacting with node1 here, I kept it in line with the Scala sample though.

2020-10-07 16:54 UTC, ignasi35 commented
Hi @johanandren, this currently has the shopping-cart service. Are you planning on also adding the analytics and the orders ones in this PR or should we merge and do the other two services in separate PRs?

2020-10-07 17:10 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-java/src/test/java/shopping/cart/IntegrationTest.java
> +        // add from client1, consume event on node3
I already changed that in `main`

2020-10-07 18:04 UTC, ignasi35 requested changes
I've reviewed the easy bits (anything except Java code). Left a few minor suggestions.

I'll review the Java code tomorrow.

2020-10-08 09:51 UTC, patriknw approved these changes
LGTM. A few quick ones, but otherwise I think we can merge this and take it from here.

2020-10-08 09:51 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-java/src/main/java/shopping/cart/ShoppingCart.java
> +        // FIXME not very nice with akka.japi.function when type is not inferred
would look better to inline that:
```
ClusterSharding.get(system).init(Entity.of(ENTITY_KEY, entityContext -> {
            int i = Math.abs(entityContext.getEntityId().hashCode() % TAGS.size());
            String selectedTag = TAGS.get(i);
            return ShoppingCart.create(entityContext.getEntityId(), selectedTag);
        }));
```

2020-10-08 09:51 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-java/src/main/java/shopping/cart/ShoppingCart.java
> +        super(PersistenceId.of(ENTITY_KEY.name(), cartId));
above FIXME onPersistFailure can be solved here, second parameter to `super`:
```
SupervisorStrategy.restartWithBackoff(Duration.ofMillis(200), Duration.ofSeconds(5), 0.1))
```

2020-10-08 09:51 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-java/src/main/java/shopping/cart/ShoppingCartServiceImpl.java
> +                // FIXME from scala sample, but how is this always INVALID_ARGUMENT??
I think that is when the askWithStatus returns a failure, and that is when the ShoppingCart rejects commands

2020-10-08 09:53 UTC, patriknw commented
Add testing in `.travis`

2020-10-08 10:39 UTC, ignasi35 approved these changes

2020-10-08 10:39 UTC, ignasi35 commented
@johanandren I think this only needs `Add testing in .travis` and we'll be good to go.

2020-10-08 13:45 UTC, johanandren commented
Looks like the PR validation does not involve travis so no idea if that maven addition works or not.

2020-10-08 13:52 UTC, patriknw commented
That is strange. It worked a few days ago. Here is the latest build that was validated https://github.com/akka/akka-platform-guide/pull/250, and those from today were not.

2020-10-08 14:02 UTC, patriknw commented
I clicked some check in the branch protection settings. Don't know why/if that changed.

2020-10-08 14:10 UTC, patriknw commented
I'll start next step here, which is adding the order and analytics services

2020-10-08 14:37 UTC, ignasi35 commented on .travis.yml
> +  - export PATH=$M2_HOME/bin:$PATH
Isn't maven installed out of the box in Travis? I think it Just Works ™️ in other builds (like https://github.com/lagom/lagom-samples/blob/1.6.x/.travis.yml)

2020-10-08 15:01 UTC, patriknw commented
That still doesn't trigger a build.
This PR has been built before https://travis-ci.com/github/akka/akka-platform-guide/builds/187224196

2020-10-08 15:53 UTC, johanandren commented on .travis.yml
> +  - export PATH=$M2_HOME/bin:$PATH
No idea, copied the akka-samples setup. I can try without it.

2020-10-09 09:15 UTC, patriknw commented
@johanandren could you also run `scripts/copy-identical-files.sh`

2020-10-09 11:37 UTC, patriknw commented
one test failed twice now, I'll look into that

2020-10-09 11:50 UTC, johanandren commented
thx, something with cluster forming that is flakey

2020-10-09 12:09 UTC, patriknw commented
it was just too short timeout

2020-10-09 12:09 UTC, merged