Add docker instructions to dev-env.adoc
akka/akka-platform-guide pull request #238
Opened 2020-10-02 16:27 UTC by octonato

2020-10-02 16:34 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +== grpcurl
I changed the order here to follow the order during development.

* start docker
* run locally with sbt
* do some calls with grpcurl

2020-10-02 16:34 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> -== grpcurl
moved down, to after starting the server

2020-10-02 16:34 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +To verify that the events are actually saved, and the state can be recovered from the events you can stop the service with `ctrl-c` and then start it again.
This was a grammar recommendation from JetBrains ;-)

2020-10-02 16:34 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +include::dev-env.adoc[tag=docker]
@patriknw, I didn't add a link to dev-env for troubleshooting, but simply included the whole section. Users don't need to go back and forth.

2020-10-02 16:34 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/projection-query.adoc
> +include::dev-env.adoc[tag=dockerImportant]
Here we include only the troubleshooting part, not need to warn about keyspace settings.

2020-10-02 16:34 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +[IMPORTANT]
Two kinds of admonitions as defined here https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#paragraphs

2020-10-05 12:40 UTC, ignasi35 requested changes

2020-10-05 12:40 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +This tutorial makes used of Cassandra and Kafka. You may use local installations during development, but we recommend run both servers using https://docs.docker.com[Docker]. The template project incl
```suggestion
This tutorial uses Cassandra and Kafka. You may run local installations during development, but we recommend running both services using https://docs.docker.com[Docker]. The template project includes a https://docs.docker.com/compose/[Docker Compose] file on its root you can use to run Cassandra and Kafka. The provided Docker Compose file also runs Zookeeper which is required to run a Kafka broker.
```

2020-10-05 12:40 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +This tutorial makes used of Cassandra and Kafka. You may use local installations during development, but we recommend run both servers using https://docs.docker.com[Docker]. The template project incl
Ths links to docker and docker-compose are valid asciidoc syntax but don't adhere to the style required for external links:

    https://some-domain.org/foo[Link text] https://some-domain.org/foo[{tab-icon}, window="tab"]

2020-10-05 12:40 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +After installing `docker` and `docker-compose`, you can run the following command at the root of the project.
It'd be good to link to the installation instructions of both docker and docker-compose here.

2020-10-05 12:40 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +After installing `docker` and `docker-compose`, you can run the following command at the root of the project.
> [...] you can run the following command at the root of the project

I can run that command, but why? ;-)

PS. also, when introducing a snippet, especially if using the word "following" prefer ending the sentence with a colon `:`.

2020-10-05 12:40 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +Create the Cassandra keyspace and tables with:
Users that preferred _not_ using docker compose, may not see this as a required step.

IMHO, creating the tables in the DB should not be under the `== Docker and Docker Compose` section but a  dedicated one, instead.

2020-10-05 12:40 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +[IMPORTANT]
I also prefer the syntax:

```
[FOO]
=====
some text
====
```

for admonitions.

2020-10-05 12:40 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +include::dev-env.adoc[tag=docker]
I think it adds too much noise. I'd rather right-click, do what I need to do, and close the new tab.

2020-10-05 12:40 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/projection-query.adoc
> +include::dev-env.adoc[tag=dockerImportant]
This `include`, OTOH, looks appropriate since it'll help prevent issues.

2020-10-05 15:08 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +After installing `docker` and `docker-compose`, you can run the following command at the root of the project.
What do you mean why? Do you think we should explain why docker is a good idea?

I would rather not explain everything. If we say that we recommend something and provide the links, and users have no idea what is that, they can ignore the recommendation or research, no?

Otherwise we will add to much information in our guide. Most people are not already familiar with docker and will understand why we recommend it.

2020-10-05 15:08 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +After installing `docker` and `docker-compose`, you can run the following command at the root of the project.
```suggestion
After installing `docker` and `docker-compose`, you can run the following command at the root of the project:
```

2020-10-05 15:08 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +Create the Cassandra keyspace and tables with:
This is still a required step for them. We want to add this here because we want to show how to load it in docker. 

If a user prefers to run Cassandra and Kafka locally, they are on their own. I would assume that they are comfortable enough to see `ddl-scripts/create_tables.cql` and understand that they should pass it to cqlsh.

2020-10-05 15:08 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +include::dev-env.adoc[tag=docker]
I don't know. The goal was exactly to avoid context switching. 

Later on, I also add this again when creating the projection table, but only the troubleshooting part. The instructions are slightly different and it doesn't make sense to put a link. So, I opt to include the full instruction each time, so we have homogeneity.

2020-10-05 15:10 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +This tutorial uses Cassandra and Kafka. You may run local installations during development, but we recommend running both services using https://docs.docker.com[Docker]. The template project includes
note to self: change the links to open on another tag

2020-10-06 07:45 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +include::dev-env.adoc[tag=docker]
Hmmm, I see. Let me have a second look. I'll actually run the site to get a better feel.

2020-10-06 07:54 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +After installing `docker` and `docker-compose`, you can run the following command at the root of the project.
I meant that the following sentence may be a bit more understandable:

```
After installing `docker` and `docker-compose`, use the following command at the root of the project to start Cassandra and Kafka:  
```

What I meant with `but why?` is that we either assume they know nothing and explain everything in detail or we assume they are familiar with docker/docker-compose and don't even bother detailing the command.

2020-10-06 07:55 UTC, ignasi35 approved these changes

2020-10-06 08:02 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +This tutorial uses Cassandra and Kafka. You may run local installations during development, but we recommend running both services using https://docs.docker.com[Docker]. The template project includes
@octonato I'll do that and push to your branch.

2020-10-06 09:30 UTC, patriknw approved these changes
LGTM

2020-10-06 09:30 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +include::dev-env.adoc[tag=docker]
I think it's ok to repeat. It's not in each and every Run section.

2020-10-06 12:55 UTC, merged