Partial pass.
akka/akka-platform-guide pull request #266
Opened 2020-10-07 17:58 UTC by rstento

@patriknw @ignasi35 This PR represents only a partial pass (up to the Create Entity page) of the scala tutorial. But, because I'm proposing a different numbering scheme, I wanted you to see it, and hopefully approve it, before I continue in this vein. I also haven't tried the steps myself yet, I wanted to get a full overview first. I also didn't want to diverge too far because I see that there is still ongoing work. Once you've reviewed and accepted what you like, I'll continue.

2020-10-08 07:17 UTC, patriknw reviewed
I like the new numbering scheme and split of dev env setup and project setup.
Most other edits are also great. Thanks

2020-10-08 07:17 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/pages/index.adoc
> +This tutorial illustrates how microservices can interact to implement a shopping cart system. It demonstrates use of the following Akka Platform features:
I don't like having the links to reference docs at the top of this page. There is a risk that they go there and don't come back. I want them to dive in to the tutorial first.

2020-10-08 07:17 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/pages/index.adoc
> +ifdef::review[REVIEWERS: Not sure why the page listing is in a partial, there isn't a use case for sharing it (including in multiple places), is there?]
I don't know what that means

2020-10-08 07:17 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/pages/overview.adoc
> +This tutorial shows how to build the functionality for a Shopping Cart system. When complete, end users will be able to add items to a cart and checkout, creating an order. Analytics also measure ite
it's not only gRPC, it's also using Kafka, as transport mechanism

2020-10-08 07:17 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/pages/overview.adoc
> +This tutorial shows how to build the functionality for a Shopping Cart system. When complete, end users will be able to add items to a cart and checkout, creating an order. Analytics also measure ite
> Analytics also measure item popularity

Analytics Service and ItemPopularity are two completely different things.

Popularity count is aggregated by the PopularityProjection and stored in the query db. All inside the Shopping Cart Service.

Analytics Service is another external service.

2020-10-08 07:17 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/pages/overview.adoc
> +ifdef::review[REVIEWERS: with the next and prev buttons in the new template, not sure that we need the full list of reproduced here again?]
I guess it was to give a full overview of what is coming, but maybe that is clear enough from the nav bar

2020-10-08 09:49 UTC, ignasi35 approved these changes
Left a few more comments.

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +See the instructions for installing https://docs.docker.com/get-docker/[Docker {tab-icon}, window="new"] and https://docs.docker.com/compose/install/[Docker Compose {tab-icon}, window="tab"] on your
Is there a rule to help us decide when to use `window="new"]` and when so use `window="tab"]`?

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +ifdef::review:[REVIEWERS: in the new UI template that we will have soon, each page will have a next and previous link with the full page title, which will eliminate the need for the Learn More sectio
```suggestion
ifdef::review[REVIEWERS: in the new UI template that we will have soon, each page will have a next and previous link with the full page title, which will eliminate the need for the Learn More section, unless you have links other than to the next and prev that you want to supply. I've left them in for now.]
```

This warning was not showing on my HTML (I'm comparing the source code with the rendered HTML). There's an extra `:`.

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +ifdef::review:[REVIEWERS: in the new UI template that we will have soon, each page will have a next and previous link with the full page title, which will eliminate the need for the Learn More sectio
+1 to keeping the `Learn More` section.

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> += IV: Create Event Sourced Cart entity
```suggestion
= IV: Create the Event Sourced Cart entity
```

? (it sounded strange without the `the`).

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/template.adoc
> +ifdef::review[REVIEWERS: we should add what they will see if successful and what to do if not.]
👍🏼

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/template.adoc
> +docker-compose up -d
```suggestion
// # tag::docker[]
. From the root project directory, run the following command:
+
----
docker-compose up -d
```

Adding the tag between the list item and the snippet breaks the look.

Also, including the sentence `From the root project directory, run the following command` inside the tagged section looks better when embeddeding the tagged section elsewhere.

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/template.adoc
> +====
```suggestion
// # end::dockerImportant[]
+
It will create the keyspace and all tables needed for Akka Persistence as well as the offset store table for Akka Projection.
+
[CAUTION]
====
The keyspace as created by the script works fine for local development but is probably not what you need in a production environment. 
====
```

I think all these paragraphs are related and need the `+`  continuation.

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/nav.adoc
>  * xref:projection-kafka.adoc[Projection publishing to Kafka]
~@rstento are the last few steps not numbered on purpose?~

~When seeing the roman numerals in this change I thought you were suggesting the change and stopped adding the roman numerals for us to pick up. After reviewing more contents on this PR I realize you consistently stopped numbering steps of the tutorial after `IV.`.~

_You only changed the names of the pages you've already reviewed_ 😊

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/nav.adoc
>  * xref:projection-kafka.adoc[Projection publishing to Kafka]
Another nitpick. Should we use `IV:` (uses colon)  or `IV.` (uses period)?

I think asciidoc's automatic numbering of lists when [using roman numerals uses the period](https://asciidoctor.org/docs/user-manual/#numbering-styles).

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/grpc-service.adoc
> +First, create a protobuf service descriptor file: `src/main/protobuf/ShoppingCartService.proto`. Define the service interface as shown.
@rstento we have an ongoing proposal to change how embedded code is displayed in #227. Using asciidoctor's [syntax for embedded code](https://asciidoctor.org/docs/user-manual/#applying-source-highlighting) we prefix any snippet with the file name so we don't have to do it on the paragraph immediately before it. So, instead of:

```
First, create a protobuf service descriptor file: `src/main/protobuf/ShoppingCartService.proto`. Define the service interface as shown. 

[source,protobuf]
----
include::example$01-shopping-cart-service-scala/src/main/protobuf/ShoppingCartService.proto[]
----
```

We can do:


```
First, create a protobuf service descriptor file with the content: 

.src/main/protobuf/ShoppingCartService.proto
[source,protobuf]
----
include::example$01-shopping-cart-service-scala/src/main/protobuf/ShoppingCartService.proto[]
----
```

This makes the text a bit simpler and moves the Language-especific file name to the metadata of the embedded code (so we have fewer language-specific content in paragraphs). 

Also, moving that info the the snippet metadata we can then theme how to show the information and (potentially) use that info to create a link or something more advanced.

I'd like your opinion on this approach, but I'd rather discuss it on #227

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/grpc-service.adoc
> +:!sectnums:
TIL about `sectnums`. Love it!

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +ifdef::review[REVIEWERS: re: bullet 3 above, I didn't see any explanation of how to distribute entities in the rest of the page. Maybe because it's part of deploying in the cloud, which isn't written
The callout `<1>` on the snippet of code in the `Initialization` section mentions cluster distribution.  Y U nO sEe iT? :-) (joking)

We'll make more emphasis on that.

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +If you are unfamiliar with Event Sourcing, refer to the xref:concepts:event-sourcing.adoc[Event Sourcing] section for an explanation.
Nice! 👍🏼

2020-10-08 09:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/overview.adoc
> +xref:projection-grpc-client.adoc[Projection calling gRPC service]
@rstento  Both here and in `nav.adoc` you specify the full name of the page you point to. We could just leave the link blank and Antora will do it for us. So, instead of:

```
xref:dev-env.adoc[I. Set up your development environment]
xref:grpc-server.adoc[II. First gRPC service]
xref:entity.adoc[III. Event Sourced entity]
xref:complete-entity.adoc[IV. Complete Event Sourced entity]
xref:projection-query.adoc[Projection for queries]
```

we can

```
xref:dev-env.adoc[]
xref:grpc-server.adoc[]
xref:entity.adoc[]
xref:complete-entity.adoc[]
xref:projection-query.adoc[]
```

And the final HTML result is identical. Plus we don't need to maintain copies of the text.

Is there an advantage I am missing in duplicating the text?

2020-10-08 09:50 UTC, ignasi35 requested changes
Sorry, pressed the wrong buttons

2020-10-08 15:17 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +To follow tutorial steps you will need a code editor, a build tool, and `grpcurl` (a CLI for sending gRPC calls). You can use your preferred code editor. We provide the steps for using https://www.je
@ignasi35, yes, I think it is simpler to implement, but more importantly easier for the reader. They know that clicking will open a new tab and they don't lose their place in our doc.

2020-10-08 15:22 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +This tutorial uses Cassandra and Kafka. You may run local installations during development, but we recommend running both services using https://docs.docker.com[{tab-icon}, window="tab"]. The templat
I've just fixed the docker link.

2020-10-08 15:24 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +ifdef::review:[REVIEWERS: in the new UI template that we will have soon, each page will have a next and previous link with the full page title, which will eliminate the need for the Learn More sectio
Yup agreed that they are good where appropriate. I've modified the reviewer note to reflect that.

2020-10-08 15:25 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/index.adoc
> +This tutorial illustrates how microservices can interact to implement a shopping cart system. It demonstrates use of the following Akka Platform features:
Agreed, this is a perfect place for a learn more section. I'll move the links to that but leave the bulleted list of features.

2020-10-08 15:34 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/index.adoc
> +ifdef::review[REVIEWERS: Not sure why the page listing is in a partial, there isn't a use case for sharing it (including in multiple places), is there?]
Instead of the links being in-line, they are included with this statement: include::partial$listing.adoc[] Usually the reason you would do that is if you were using them in more than one place. Since they aren't being used in more than one place, it is just simpler to include them inline, for future editors.

2020-10-08 15:35 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/overview.adoc
> +This tutorial shows how to build the functionality for a Shopping Cart system. When complete, end users will be able to add items to a cart and checkout, creating an order. Analytics also measure ite
Added Kafka.

2020-10-08 15:36 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/overview.adoc
> +ifdef::review[REVIEWERS: with the next and prev buttons in the new template, not sure that we need the full list of reproduced here again?]
I'll leave it for now, easy to remove if it seems to be too heavyweight later.

2020-10-08 15:39 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +. https://www.jetbrains.com/idea/download/[install IntelliJ]
Yes, good catch, fixed.

2020-10-08 15:41 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +. From the *Preferences* menu, add the `sbt` plugin.
Yes, the latter, each step s/be a sentence, I've fixed.

2020-10-08 15:44 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/overview.adoc
> +xref:projection-grpc-client.adoc[Projection calling gRPC service]
Now you've taught me one. I don't think that earlier versions of Antora did this. I tried it early on. Thanks!

2020-10-08 16:00 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +ifdef::review[REVIEWERS: re: bullet 3 above, I didn't see any explanation of how to distribute entities in the rest of the page. Maybe because it's part of deploying in the cloud, which isn't written
Si, now I C it in the callout, but was looking for more in the introduction. :-). Modified the note and will leave it in here for a reminder.

2020-10-08 16:01 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/grpc-service.adoc
> +:!sectnums:
👍

2020-10-08 16:47 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/overview.adoc
> +This tutorial shows how to build the functionality for a Shopping Cart system. When complete, end users will be able to add items to a cart and checkout, creating an order. Analytics also measure ite
I'm just going to remove that sentence for now then. It is probably getting into too much detail.

2020-10-08 16:48 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +The https://github.com/fullstorydev/grpcurl[grpcurl {tab-icon}, window="tab"] tab is useful for making gRPC calls from the command line. It is used in tutorial procedures and we recommend that you in
fixed.

2020-10-08 16:57 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +See the instructions for installing https://docs.docker.com/get-docker/[Docker {tab-icon}, window="new"] and https://docs.docker.com/compose/install/[Docker Compose {tab-icon}, window="tab"] on your
@ignasi35, it's an arbitrary value. In some browsers, when you use a different name for the window in two different links, it will open a separate tab for each. Not always though. In this case, it would open one for the installing page of the Docker dock and another for the Compose page. I didn't do it intentionally. I'm just more accustomed to calling the window new and didn't even notice the difference.

2020-10-08 16:58 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +ifdef::review[REVIEWERS: I was not sure whether this section belongs here or where they actually will need to use it. I found the following confusing, it says that the template includes the config fo
OK, I'll leave the note in there and leave it up to the team.

2020-10-08 18:09 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> += IV: Create Event Sourced Cart entity
Agreed, changed.

2020-10-08 18:15 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/grpc-service.adoc
> +First, create a protobuf service descriptor file: `src/main/protobuf/ShoppingCartService.proto`. Define the service interface as shown.
Added the colon as suggested by Patrik and commented on #227.

2020-10-08 18:17 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/grpc-service.adoc
> +ifdef::review[REVIEWERS: it appears as though the impl class is in a separate file, do we need to explicitly tell the reader where to put it?]
@patriknw, we can create the tabs using the current theme. I'll do some examples tomorrow and we can look at the best way to address this issue.

2020-10-08 18:20 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/template.adoc
> +docker-compose up -d
Right you are, good catch. I fixed it.

2020-10-08 18:23 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/template.adoc
> +====
I often do a summary at the bottom that is out of the numbered list. That is how I considered this, but it works just as well at the same inset. I've changed as you suggested.

2020-10-08 18:25 UTC, rstento commented
@ignasi35 & @patriknw, I think I addressed all of your comments, but it still says 1 change is requested and I can't find it.

2020-10-09 07:30 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/pages/grpc-service.adoc
> +ifdef::review[REVIEWERS: it appears as though the impl class is in a separate file, do we need to explicitly tell the reader where to put it?]
I tried in https://github.com/akka/akka-platform-guide/pull/271/files#r501693069

2020-10-09 08:43 UTC, ignasi35 commented
> but it still says 1 change is requested and I can't find it

that's because I (as a reviewer) requested changes in the past and I haven't accepted the changes yet. It's not that some discussion is pending.

2020-10-09 08:45 UTC, ignasi35 commented
@rstento the new changes look good to me. 

My question now is whether you think we should merge already. Every edit in this PR seems to aligned with what @patriknw or I commented but the PR itself is not a _complete_ review (the last few steps of the tutorial aren't reviewed, if I understand correctly).

2020-10-09 12:14 UTC, patriknw commented
I'd suggest that we merge this and @rstento can continue in new PR. Less risk that it becomes outdated with merge conflicts and such.

2020-10-09 15:48 UTC, patriknw approved these changes
LGTM, merging this as the first step and you can continue in another PR.
I'll follow up on the reviewer comments next week.

2020-10-09 15:49 UTC, merged