Add links to download source zip files
akka/akka-platform-guide pull request #296
Opened 2020-10-14 15:34 UTC by octonato

References #61

2020-10-14 15:39 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +****
In order to make it visible, I chose to use such a block. 

It displays like the following. 

![CleanShot 2020-10-14 at 17 34 38](https://user-images.githubusercontent.com/502982/96011838-bf4ca100-0e43-11eb-9476-87d1840ad24b.png)

2020-10-14 15:39 UTC, octonato commented on scripts/prepare-downloads.sh
> +zipAndAttach shopping-cart-service-start.zip
using numbered zips files is not ideal because people won't know what they have inside and from which step they come from. 

Alternatively, we append a number, but I don't think the number should reflect the step number, only the ordering. Like this, for example:

```
Permissions Size User   Group Date Modified Name
.rw-r--r--@ 12Ki renato staff 14 Oct 16:56  0-shopping-cart-service-start.zip
.rw-r--r--@ 14Ki renato staff 14 Oct 16:57  1-shopping-cart-service-grpc.zip
.rw-r--r--@ 21Ki renato staff 14 Oct 16:57  2-shopping-cart-service-event-sourced.zip
.rw-r--r--@ 22Ki renato staff 14 Oct 16:57  3-shopping-cart-service-event-sourced-complete.zip
.rw-r--r--@ 29Ki renato staff 14 Oct 16:58  4-shopping-cart-service-projection.zip
.rw-r--r--@ 46Ki renato staff 14 Oct 16:58  6-shopping-cart-service-projection-kafka.zip
.rw-r--r--@ 63Ki renato staff 14 Oct 16:58  7-shopping-cart-service-complete.zip
```

`0-` is the seed (like the g8 template). 

Once I have downloaded them all, they are ordered in my directory as such. 

WDYT?

2020-10-14 16:32 UTC, octonato commented
Btw, I pushed a new change. All zip files have now a `-scala` are the end. We need it as we start to add the java examples.

2020-10-15 08:24 UTC, patriknw commented on scripts/prepare-downloads.sh
> +zipAndAttach shopping-cart-service-projection-kafka-scala.zip
since some of the zips also contain analytics and order service I think we should name them `shopping-projection-kafka-scala.zip`

2020-10-15 08:24 UTC, patriknw commented on scripts/prepare-downloads.sh
> +zipAndAttach shopping-cart-service-projection-kafka-scala.zip
could also be nice to have a number prefix in the name `05-shopping-projection-kafka-scala.zip`

2020-10-15 08:24 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/pages/projection-query.adoc
> +****
I wonder if we should only link to the initial source here, and then have another link at the end (before Run) with link to the completed source?

2020-10-15 11:00 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +****
Looks great!

2020-10-15 11:02 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +****
This look may even work for "Learn more" #235

2020-10-15 11:06 UTC, ignasi35 commented on scripts/prepare-downloads.sh
> +zipAndAttach shopping-cart-service-start.zip
I think numbering the files to keep things sorted is useful. I would use `3-akka-microservices-tutorial-...zip` instead (or `akka-microservices-tutorial-03-event-sourced-complete.zip`.

The final few steps are ZIP files that contain more than just the shopping cart service and these are attachments to the microservices tutorial. I mean, 3 months from now, when I find that ZIp file on my hard drive, the name `akka-microservices-tutorial-...zip` will give me more background.

2020-10-15 11:08 UTC, ignasi35 commented on scripts/prepare-downloads.sh
> +zipAndAttach shopping-cart-service-projection-kafka-scala.zip
will repeat my idea here:

* +1 to numbering for ordering
* i'd use `akka-microservices-tutorial-...` in the name instead of `shopping-cart`

2020-10-15 11:18 UTC, ignasi35 requested changes

2020-10-15 11:18 UTC, ignasi35 commented on .gitignore
> +docs-source/docs/modules/microservices-tutorial/assets/attachments/*.zip
👍

2020-10-15 11:18 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +If you prefer to skip the tutorial and have a study on the full example implementation on your own, you can download it link:{site-url}/assets/attachments/shopping-cart-service-complete-scala.zip[her
why is this link a `{site-url}/...` instead of `link:_attachments/...`?

2020-10-15 11:18 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +You can download the initial source for this section link:_attachments/shopping-cart-service-event-sourced-scala.zip[here] +
What is that `+` there? Aren't two consecutive lines rendered as a single paragraph?

2020-10-15 11:18 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +You can download the initial source for this section link:_attachments/shopping-cart-service-event-sourced-scala.zip[here] +
Nitpick. We refer to each page in the tutorial with many different words: `section`, `step`, `part`,... we could converge to a single term.

2020-10-15 11:18 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/grpc-service.adoc
> -In this section, you will learn how to:
This should be reverted. @rstento explicitly added the `In this section,` on each page (but she only managed to complete the review of pages `I.` to `III.` (hence the inconsistency).

2020-10-15 11:18 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/grpc-service.adoc
> -In this section, you will learn how to:
By `inconsistency` I mean that sections, where the title is not a roman numeral, are probably not consistent and should be considered as unreviewed.

2020-10-15 11:18 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/projection-query.adoc
> +****
I had a similar though.

Also, making the link be on a `here` word sounds weird. Maybe @rstento has some thoughts.

2020-10-15 12:56 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +If you prefer to skip the tutorial and have a study on the full example implementation on your own, you can download it link:{site-url}/assets/attachments/shopping-cart-service-complete-scala.zip[her
That's wrong. I used {site-url} on my first trial. I will fix it.

2020-10-15 13:00 UTC, octonato commented on scripts/prepare-downloads.sh
> +zipAndAttach shopping-cart-service-projection-kafka-scala.zip
I think `akka-microservices-tutorial` is too long. We still need to append the name of the step. 

`shopping-cart` for me is ok, if users download it somewhere they will know that they did it while following the akka microservices guide. And if not, well, they can look inside to refresh their memory.

2020-10-15 14:37 UTC, patriknw commented on scripts/prepare-downloads.sh
> +zipAndAttach shopping-cart-service-projection-kafka-scala.zip
`01-shopping-example-` ?

`01-shopping-cart-` is also fine if you prefer that

2020-10-15 14:46 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/projection-query.adoc
> +****
I think it makes at the start, so you can decide which path to follow: active or passive. 

I will work out the other open points here and then experiment with some alternatives.

2020-10-15 14:53 UTC, patriknw commented on docs-source/docs/modules/microservices-tutorial/pages/projection-query.adoc
> +****
ok, we can try this first.

2020-10-15 15:00 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +You can download the initial source for this section link:_attachments/shopping-cart-service-event-sourced-scala.zip[here] +
I think we should call it step then. 

Section is what a page has, like a header. You can link to sections. Here we are talking about tutorial steps. 

I will change.

2020-10-15 15:03 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/grpc-service.adoc
> -In this section, you will learn how to:
I think I only saw it here. Do I understand correctly that we should have `In this section, you will learn how to:` each time? 

I also found it better, but removed because it was the only one.

2020-10-15 15:36 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +You can download the initial source for this section link:_attachments/shopping-cart-service-event-sourced-scala.zip[here] +
> What is that + there? Aren't two consecutive lines rendered as a single paragraph?

Didn't try with double space. Read in the docs that I should use a +

2020-10-15 15:38 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +****
Something happened with between yesterday and today, because now it's displaying like that. 

![CleanShot 2020-10-15 at 17 33 52](https://user-images.githubusercontent.com/502982/96152676-18343c00-0f0d-11eb-8409-28af987e6813.png)

@rasummer, any idea of what my have happened?

2020-10-15 15:43 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +****
@ignasi35, I re-worked this part. 

* referring to it as "this tutorial step"
* links are on the thing we can download: "initial source" and "completed source"

2020-10-15 15:43 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +****
@ignasi35, I re-worked this part. 

* referring to it as "this tutorial step"
* links are on the thing we can download: "initial source" and "completed source"

2020-10-15 15:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +****
@octonato have you rebased?

2020-10-15 15:49 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +****
```suggestion
.Download source code
****
You can download the link:_attachments/2-shopping-cart-event-sourced-scala.zip[initial source] for this tutorial step (includes code from the previous step).

Or, if you prefer, you can download the link:_attachments/3-shopping-cart-event-sourced-complete-scala.zip[completed source] for this tutorial step.
****
```

OK, if we adopt `step` then we should create an issue to do a full review (not just the new usages added in this PR).

2020-10-15 15:50 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +****
In my previous comment I'm referring to sentences like `In this section, you will learn how to:`.

2020-10-15 17:40 UTC, ignasi35 approved these changes

2020-10-15 17:47 UTC, rstento requested changes

2020-10-15 17:47 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +In this section, you will learn how to:
Since this is one HTML page with multiple sections with multiple steps, I suggest saying:

On this page you will learn:

With this construction, the bullets don't always have to be how to, they can also be concepts:

- how to ....
- about ....

2020-10-15 17:47 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/complete-entity.adoc
> +****
How about:

Available .zip downloads:

* Source that includes all previous tutorial steps and allows you to start with the steps on this page. 
* Source with the steps on this page completed.

2020-10-15 17:47 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +We encourage entering the code described in the tutorial, even if you just copy and paste. If you get stuck or prefer to skip over some parts you can download a zip file containing the complete sourc
We encourage you to enter the example code, even if by copying and pasting. If you get stuck or prefer to skip some main steps, we provide source files for download. The introduction of each page with tutorial development steps includes links to two zip files: one with completed source up to that point, and one with completed source for the steps described on that page.

2020-10-15 17:47 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/dev-env.adoc
> +If you prefer to skip the tutorial and study the full example implementation on your own, you can download it link:_attachments/6-shopping-cart-complete-scala.zip[here].
hmm, I wouldn't suggest that they skip the tutorial entirely. If they try to learn on their own, they will likely miss a lot. How about:

If you would like to run the full example, you can download the full implementation from [here]. In this case, we suggest you scan the tutorial instructions to identify the source files that you can learn from.

2020-10-15 17:47 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +In this section, you will learn how to:
On this page?

2020-10-15 17:47 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +.Download source code
same comment as previous.

2020-10-15 17:47 UTC, rstento commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +.Download source code
and ditto for the ones below.

2020-10-15 18:25 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +.Download source code
which previous comment? I didn't find any related to "Download source code".

2020-10-15 18:27 UTC, octonato commented
@rstento, I applied your suggestions. 

I will merge this one when Travis finishes the build. Please, if you have any other changes, let me know and I will do it on another PR. 

I would like to merge this one by now because I have some other stuff depending on it.

2020-10-15 18:28 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +.Download source code
ah, I found it. Will do

2020-10-15 18:32 UTC, octonato commented on docs-source/docs/modules/microservices-tutorial/pages/entity.adoc
> +.Download source code
For the first page, I will do it slightly different: 

* Source with initial project template. Alternatively, use `sbt` to start a new project as explained in xref:template.adoc[Run the template].
* Source with the steps on this page completed.

2020-10-15 18:55 UTC, merged