A spike to move to sdkman
akka/akka-platform-guide pull request #308
Opened 2020-10-16 08:02 UTC by ignasi35

References https://github.com/akka/akka-meta/issues/141

Blindly trying things...

2020-10-16 08:03 UTC, ignasi35 commented on .travis.yml
> +  - sdk use sbt 1.3.13
Use `sbt` provided by sdkman, because why not.

2020-10-16 08:03 UTC, ignasi35 commented on .travis.yml
All the caching management is inherited from the parent build.

2020-10-16 08:30 UTC, ignasi35 commented
Something's weird:

```
sbt -jvm-opts .jvmopts-travis "test; scalafmtCheckAll"
[info] welcome to sbt 1.3.13 (AdoptOpenJDK Java 1.8.0_265)
...
[info] set current project to shopping-cart-service (in build file:/Users/ignasi/git/github/akka/akka-platform-guide/main/docs-source/docs/modules/microservices-tutorial/examples/shopping-cart-service-scala/)
[error] Expected ';'
[error] -jvm-opts
```

2020-10-16 10:04 UTC, ignasi35 commented on .travis.yml
> +  - sdk use sbt 1.3.13
This is vanilla `sbt` instead of the Travis-provided `sbt-extras`. As a consequence, we can no longer use `-jvm-opts` but we were not using them anyway:

 - when we invoked `sbt -jvm-opts .jvmopts-travis` we had already `cd`'d into a folder with no `.jvmopts-travis`

2020-10-16 10:04 UTC, ignasi35 commented on .travis.yml
> +        - sbt "test; scalafmtCheckAll"
We can eventually remove the `ls -la` and the `pwd` but they were useful to debug.

2020-10-16 10:17 UTC, ignasi35 commented on .travis.yml
> +import: scala/scala-dev:travis/default.yml
Use `scala-dev`'s parent build.

2020-10-16 10:17 UTC, ignasi35 commented on .travis.yml
> +language: java
Using `java` instead of `scala` so not `sbt` is installed out of the box (we'll use the one installed by sdkman)

2020-10-16 10:18 UTC, ignasi35 commented on .travis.yml
> +language: java
Note: changing the language also had the nice side-effect that the polluted cache was no longer visible because travis caches by language/branch/etc...

2020-10-16 13:35 UTC, ennru requested changes
Let's hold this off until we agree on a general direction for CI.

2020-10-16 13:48 UTC, ignasi35 commented
@ennru even if we don't merge this PR, we should keep in mind these diffs:

```diff
- sbt -jvm-opts .jvmopts-travis "test; scalafmtCheckAll"
+ sbt "test; scalafmtCheckAll"
```

which I sneaked into this PR.

It doesn't matter if we stay on travis or move to some other CI provider, we should no longer use `-jvm-opts .jvmopts-travis` in the jobs.

2020-10-16 13:54 UTC, ennru commented
I added it (in many repos) to make output colouring work. But that breaks with sbt 1.4.0 again anyway...

2020-10-23 08:27 UTC, ignasi35 commented
I think we can close instead of keeping it as DRAFT. We can restore it if/when we think it's the right move.

2020-10-23 08:27 UTC, closed without merging