Initial GKE ingress docs
akka/akka-platform-guide pull request #584
Opened 2021-02-18 09:25 UTC by chbatey

2021-02-18 10:47 UTC, patriknw commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> +    akka.lightbend.com/ingress-class: gce
Do I understand it correctly that enabling `grpcIngress` without also specifying this annotation (gce or alb) will not work? When we talked about annotations I thought it would be used for custom options, but we could still support the default without them?

Could we add the ingress-class as a property fo the `grpcIngress` section instead so that the default ingress can be enabled at one place?

2021-02-18 10:47 UTC, patriknw commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> +    akka.lightbend.com/ingress-class: gce
what happens if both grpcIngress and httpIngress are enabled and they need different annotations? I thought the support for annotations would be in grpcIngress/httpIngress sections rather than at the top level?

2021-02-18 11:19 UTC, chbatey commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> +    akka.lightbend.com/ingress-class: gce
> what happens if both grpcIngress and httpIngress are enabled and they need different annotations? I thought the support for annotations would be in grpcIngress/httpIngress sections rather than at the top level?

We could have separate annotations ones for http and grpc or put it as a property as you say. Annotations only work in the metadata section. 

If you don't specify any annotations you get a normal Ingress/Service that would work with any Ingress Controller that doesn't require any annotations on the Ingress resource e.g. Minikube Ingress would work. 

Given that you have to install the AWS ingress controller manually that made me think that we shouldn't just default based on the type of cluster we are in.

2021-02-18 11:53 UTC, patriknw commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> +    akka.lightbend.com/ingress-class: gce
I think we should make the choice (ingress-class) more explicit by making it an explicit property in the grpcIngress/httpIngress sections. We can still have it optional as you say.

I think I misunderstood what we would use annotations for. I thought that was for custom options (AWS LoadBalancer Controller has [massive amount of annotations](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations/) for various things). The operator would just transparently propagate them from the CR to the created Service or Ingress. That is a different story.

2021-02-18 12:12 UTC, chbatey commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> +    akka.lightbend.com/ingress-class: gce
> I think we should make the choice (ingress-class) more explicit by making it an explicit property in the grpcIngress/httpIngress sections. We can still have it optional as you say.

Agreed.

> I think I misunderstood what we would use annotations for. I thought that was for custom options (AWS LoadBalancer Controller has massive amount of annotations for various things).

I do use one like that, the gke.akka.lightend.io/backend-config but it is for our behavior, not just forwaded on.

> I thought that was for custom options (AWS LoadBalancer Controller has massive amount of annotations for various things). The operator would just transparently propagate them from the CR to the created Service or Ingress. That is a different story.

I didn't get to that but do agree it will be useful and we need to allow users to specify which annotations go where some how

2021-02-19 05:13 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> += AWS LoadBalancer Controller
shouldn't this be GKE LoadBalancer Controller ?

2021-02-19 07:52 UTC, patriknw commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> +    akka.lightbend.com/ingress-class: gce
I created a new issue for annotations https://github.com/lightbend/akka-platform-operator/issues/477

2021-02-19 10:43 UTC, chbatey commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> += AWS LoadBalancer Controller
Yep, or just "GKE Ingress" as you aren't aware what the controller is called

2021-02-22 21:31 UTC, ignasi35 commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> +ion documentation {tab-icon}, window="tab"]
```suggestion
gRPC and HTTP ingress with the https://cloud.google.com/kubernetes-engine/docs/concepts/ingress[GKE Ingress Controller {tab-icon}, window="tab"] is supported  <something seems to be missing here>
<and maybe here too> ion documentation {tab-icon}, window="tab"]
```

2021-02-22 22:18 UTC, ignasi35 requested changes
Left a few comments.

2021-02-22 22:18 UTC, ignasi35 commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> +----
```suggestion
----
kubectl create secret tls my-ingress-secret --cert dummy-cert.pem  --key dummy-key.pem
----

This is referenced from the Akka Microservice.

== Enable grpcIngress

Add the `grpcIngres` section to the deployment descriptor with class set to `gce`:

.kubernetes/shopping-cart-service-cr.yml:
[source,yaml]
----
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: shopping-cart-service
  namespace: "shopping"
  annotations:
spec:
  image: <image>
  grpcIngress:
    enabled: true
    certificate: "my-ingress-secret"
    class: "gce"
----
```

2021-02-22 22:18 UTC, ignasi35 commented on docs-source/docs/modules/deployment/pages/gcp-ingress.adoc
> +* A `BackendConfig' to configure a health check to match the readiness check
```suggestion
* an `Ingress` with the appropriate GKE annotations
* a `Service` of type `ClusterIP`
* a https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#associating_backendconfig_with_your_ingress[`BackendConfig` {tab-icon}, window="tab"] to configure a health check to match the readiness check
```

2021-02-22 22:34 UTC, ignasi35 commented
Do we require a [minimum GKE version](https://github.com/lightbend/akka-platform-operator/pull/476#discussion_r580629397)?

2021-02-24 07:04 UTC, chbatey commented
TODO: add a note about min GKE version

2021-03-04 15:44 UTC, ignasi35 commented
> TODO: add a note about min GKE version

I think this is no longer necessary. The Stable release channel is already on 1.17 (https://cloud.google.com/kubernetes-engine/docs/release-notes)

2021-03-04 16:01 UTC, ignasi35 commented
@debasishg I've pushed a couple of commits and I think this is ready for a fainl review.

Note that I rewrote the `TLS certificate` section as if the `httpIngress` section already supported TLS (ref https://github.com/lightbend/akka-platform-operator/issues/477).

2021-03-18 19:28 UTC, ignasi35 approved these changes

2021-03-18 19:29 UTC, ignasi35 commented
As discussed on the team call this is ready to merge.

2021-03-18 19:29 UTC, merged