AWS FTR doc additions
akka/akka-platform-guide pull request #602
Opened 2021-03-01 23:31 UTC by thothmoses

Additions to address AWS FTS issues
- How to manage updates to the operator
- How to manage / renew TLS certifications
- How to renew licenses
- How to get support

2021-03-01 23:31 UTC, lightbend-cla-validator commented
Hi @thothmoses,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

2021-03-02 16:51 UTC, rstento requested changes
These AWS requirements and links to important information are lost on the first page. I suggest creating a Getting started with AWS page.

2021-03-02 16:51 UTC, rstento commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +== Some key quick items
Not sure what a "key quick" item is? And, not sure this is the best place to put these imporant reminders. This is an intro page that people are likely to skip or only read above the fold. Shouldn't we have a "Getting started on AWS" page?

2021-03-02 16:51 UTC, rstento commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +There are a few items that frequently need to be dealt with. The links and info below should help you access that information quickly.
The tone of "items that frequently need to be dealt with" is a bit negative. I'd like to see a motivating paragraph maybe with a bulleted list instead of separate headings for the content that follows.

2021-03-02 16:51 UTC, rstento commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +== License expiration and renewal
What is an Akka license? I assume it is one they have purchased through AWS?

2021-03-02 16:51 UTC, rstento commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +You need a Transport Layer Security (TLS) certificate for the internet facing load balancer. Akka does not manage or create TLS certificates.
Why?

2021-03-02 16:51 UTC, rstento commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +When you want to expose an akka gRPC service through a Load balancer, you will have to provide the TLS certificate. Request or import a certificate at https://console.aws.amazon.com/acm/home[Amazon C
"select the region you are working in" from where?

2021-03-02 16:51 UTC, rstento commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +Further, you will need to provide the Amazon Resource Name (ARN) to the certificate as you create the Akka Microservice Custom Resource.
"to the certificate" or "of the certificate"?

2021-03-02 16:51 UTC, rstento commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +The Akka Cloud Platform operator will create the `ingress` which references the user's ARN.However, it is not involved in any other part of the process for TLS cert management, including renewals.
"the user's" or "your" ARN? For the "However ..." sentence, shouldn't that be stated above?

2021-03-02 16:51 UTC, rstento commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +For development and testing, you can import a self-signed certificate, which can be created as in the following example:
And what's the diff between a self-signed and Amazon-provided cert? All of this preliminary info should be provided in an overview before these steps.

2021-03-02 19:38 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +For development and testing, you can import a self-signed certificate, which can be created as in the following example:
Add details and a link to the AWS doc for Self-signed certs.

2021-03-02 19:38 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +The Akka Cloud Platform operator will create the `ingress` which references the user's ARN.However, it is not involved in any other part of the process for TLS cert management, including renewals.
thx 'your' 
It is referenced above, and I have reinforced it. But, I want a reminder here.

2021-03-02 19:38 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +Further, you will need to provide the Amazon Resource Name (ARN) to the certificate as you create the Akka Microservice Custom Resource.
Thx - 'of'

2021-03-02 19:38 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +When you want to expose an akka gRPC service through a Load balancer, you will have to provide the TLS certificate. Request or import a certificate at https://console.aws.amazon.com/acm/home[Amazon C
Changed that to hile in the ACM console, you will need to select the region you are working in.

2021-03-02 19:38 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +You need a Transport Layer Security (TLS) certificate for the internet facing load balancer. Akka does not manage or create TLS certificates.
Prepended - 'A Transport Layer Security (TLS) certificate provides privacy and data integrity between two or more communicating applications.'

2021-03-02 19:38 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +== License expiration and renewal
Ok, I have revised that section.

2021-03-02 19:38 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +There are a few items that frequently need to be dealt with. The links and info below should help you access that information quickly.
Agreed - I was using headers to make these pop more because they were below the fold.

2021-03-02 19:38 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +== Some key quick items
I am re-naming this heading and moving the info above the fold. We should have a Getting Started, but that is going to be a part of the redesign of the doc as a whole.

2021-03-03 19:21 UTC, seglo reviewed
Looking good. I think the main thing is the placement of this preliminary AWS-related information. I know AWS would prefer it front and center (i.e. on our front page), but I'm not sure that makes sense for all other users of the platform guide. I think a callout on the front page might be sufficient.

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +== Key Information
Does this section belong on the home page?  Much of it is specific to deployment on AWS. Perhaps it should be the first section of the "Installation in Amazon EKS" page.

We could reduce this front page material to a section like "Getting Started with deploying Akka Cloud Platform" with a link to the "Cloud Deployment" section, and then links to cloud specific vendors: AWS and GCP (just AWS for now).

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +- Operator — Operator management is key. You will find details on xref:deployment:aws-install.adoc[installing]
Operator might be a little ambiguous to the end user. We could begin this point with "Kubernetes Akka Operator".

"Installation and updates of the Akka Operator is key to running Akka Cloud Platform..."

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +- TLS Certificates — Users often need information about TLS Certificates. You will find the pertinent information within the xref:deployment:aws-ingress.adoc#_tls_certificate[AWS LoadBalancer Control
Instead of "Users often need information about TLS Certificates"

maybe..

"TLS certificates are required for external access to applications managed by Akka Cloud Platform..."

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +- License expiration and renewal — You may have purchased your license from the AWS Marketplace, or  directly from Lightbend. In either case the license expiration and renewal for the Akka Cloud Plat
"You may have purchased your license by subscribing to the Akka Cloud Platform product on the AWS Marketplace, ..."

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +* If the Akka Cloud Platform license expires without being renewed, your current application will continue to run, but you will no longer be able to deploy.
```suggestion
* If the Akka Cloud Platform license expires without being renewed, your current application will continue to run, but you will no longer be able to deploy or update.
```

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +* If you have acquired a term license directly from Lightbend, and it expires, your license will automatically revert into a pay-as-you-go license.
Is this describing what happens when an AWS private offer agreement expires and returns to the regular rate?

/cc @jtownley

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +* When you need to renew you license, please contact mailto:aws@lightbend.com[] with your request.
```suggestion
* When you need to renew your license, please contact mailto:aws@lightbend.com[] with your request.
```

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +To expose gRPC or HTTPS publicly to the internet you can use the https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/[AWS Load Balancer Controller {tab-icon}, window="tab"] with a h
```suggestion
To expose your application's gRPC or HTTPS endpoints publicly to the internet you can use the https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/[AWS Load Balancer Controller {tab-icon}, window="tab"] with a https://kubernetes.io/docs/concepts/services-networking/ingress/[Kubernetes Ingress {tab-icon}, window="tab"] created by the Akka Operator. This is useful when external services, or clients beyond the EKS cluster need to consume the gRPC or HTTPS endpoints.
```

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +When you want to expose an akka gRPC service through a Load balancer, you will have to provide the TLS certificate. Request or import a certificate at https://console.aws.amazon.com/acm/home[Amazon C
```suggestion
When you want to expose an Akka gRPC service through a Load balancer, you will have to provide a TLS certificate. Request or import a certificate using the https://console.aws.amazon.com/acm/home[Amazon Certificate Manager (ACM) console {tab-icon}, window="tab"]. While in the ACM console, you will need to select the region you are working in. You will need to provide the Amazon Resource Name (ARN) of the certificate as you create the Akka Microservice Custom Resource.
```

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +The Akka Cloud Platform operator will create the `ingress` which references your ARN. However, please remember that it is not involved in any other part of the process for TLS certification managemen
```suggestion
The Akka Cloud Platform operator will create the Kubernetes `Ingress` which references your TLS certificate with an https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html[Amazon Resource Name (ARN) {tab-icon}, window="tab"
]. However, please remember that the operator is not involved in any other part of the process for TLS certification management, including renewals.
```

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/deployment/pages/aws-ingress.adoc
> +When the deployment descriptor has been applied, the Akka Operator will create an `ingress`, After that you can retrieve the public address with:
```suggestion
When the deployment descriptor has been applied, the Akka Operator will create an `Ingress`, After that you can retrieve the public address with:
```

2021-03-03 19:21 UTC, seglo commented on docs-source/docs/modules/deployment/pages/aws-install.adoc
> +With the Akka Operator running, you can deploy an Akka Microservice.The next page, xref:deploy.adoc[], provides general steps.The  xref:microservices-tutorial:grpc-service.adoc#kubernetes[tutorial] i
```suggestion
With the Akka Operator running, you can deploy an Akka Microservice. The next page, xref:deploy.adoc[], provides general steps. The xref:microservices-tutorial:grpc-service.adoc#kubernetes[tutorial] includes examples of build and template files.
```

2021-03-03 19:22 UTC, seglo commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +- Operator — Operator management is key. You will find details on xref:deployment:aws-install.adoc[installing]
Or "Kubernetes Akka Platform Operator"

2021-03-03 21:17 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +== Key Information
I agree, but for now, I think is where it should live for the AWS FTR until I do the doc overhaul that is planned.

2021-03-03 21:19 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +- Operator — Operator management is key. You will find details on xref:deployment:aws-install.adoc[installing]
Done

2021-03-03 21:20 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +- TLS Certificates — Users often need information about TLS Certificates. You will find the pertinent information within the xref:deployment:aws-ingress.adoc#_tls_certificate[AWS LoadBalancer Control
Done

2021-03-03 21:23 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +- License expiration and renewal — You may have purchased your license from the AWS Marketplace, or  directly from Lightbend. In either case the license expiration and renewal for the Akka Cloud Plat
Done

2021-03-03 21:25 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +* If you have acquired a term license directly from Lightbend, and it expires, your license will automatically revert into a pay-as-you-go license.
That was my understanding per my discussion with James.

2021-03-03 21:54 UTC, seglo commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +== Key Information
Ok, if it has to stay then maybe we can rename the section title to "Key Information for Akka Cloud Platform on AWS"

/cc @jtownley

2021-03-03 22:29 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +== Key Information
Ok

2021-03-03 22:55 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +== Key Information
Done

2021-03-04 15:32 UTC, seglo reviewed
LGTM @thothmoses 

I want to give @patriknw a chance to review it before it's merged, so I'll hold off on "approving" the PR because it looks like it will get automerged if I do that.

2021-03-04 15:54 UTC, ignasi35 commented
> it looks like it will get automerged if I do that.

Despite the name, `auto-merge` will _not_  merge a PR until a human presses the `Enable auto-merge` button. This feature is meant for those scenarios when a human approves a PR but can't merge because there are external checks pending (e.g. CI, CLA, etc...).

@seglo feel free to approve the PR.

2021-03-04 15:55 UTC, seglo commented
> Despite the name, `auto-merge` will _not_ merge a PR until a human presses the `Enable auto-merge` button. This feature is meant for those scenarios when a human approves a PR but can't merge because there are external checks pending (e.g. CI, CLA, etc...).

I see. Thanks for the clarification @ignasi35 !

2021-03-04 15:55 UTC, seglo approved these changes

2021-03-04 17:04 UTC, merged