Akka Platform BOM
akka/akka-platform-guide pull request #629
Opened 2021-03-16 21:08 UTC by seglo

References https://github.com/lightbend/akka-platform-meta/issues/149

2021-03-17 09:15 UTC, patriknw reviewed
looking good, it would be some work to keep it up to date but that's probably worth it

I think it's good to have it in this repo. That's the best we have for combining many things, and we can test it with the samples.

2021-03-17 09:15 UTC, patriknw commented on akka-platform-bom/project/Dependencies.scala
> +    // FIXME: do we support 2.11 BOM's? some projects don't publish it anymore
Do you mean Scala 2.11? No, we shouldn't support that.

I even think Scala 2.13 would be enough, and not even publish bom for 2.12, because I don't see a reason why a Java user would care to use the older 2.12.

2021-03-17 09:15 UTC, patriknw commented on akka-platform-bom/project/Dependencies.scala
> +    val AkkaCloudPlatform = "1.1.10"
Not sure the version number should be synced with the operator version. I can see that both the operator and Akka libraries may change independent of each other. For example, we might want to publish a new bom to push out a security patch of akka-http.

2021-03-17 09:15 UTC, patriknw commented on akka-platform-bom/project/Dependencies.scala
> +// FIXME: wait for 3.0.0 (Alpakka), 2.1.0 (Alpakka Kafka), for Akka 2.6?
will akka-stream-alpakka-cassandra be backwards compatible in a way that it can be used with akka-projection-cassandra and akka-persistence-cassandra?

Why wait? Wouldn't we just release a new bom when it's out?

2021-03-17 09:15 UTC, patriknw commented on akka-platform-bom/build.sbt
> +    bomIncludeModules := Seq(akkaCoreBom, akkaHttpBom) ++ akkaManagement,
nice that the other boms can be included

2021-03-17 12:04 UTC, ignasi35 requested changes

2021-03-17 12:04 UTC, ignasi35 commented on akka-platform-bom/build.sbt
> +    bomIncludeModules := Seq(akkaCoreBom, akkaHttpBom) ++ akkaManagement,
We will need to test this. Details like the order in which the BOMs are declared in the user code or the depth in the Maven dependency tree can affect the version resolution.

See the paragraph on [`Note that using BOM's comes with its own set of problems...`](https://github.com/lightbend/akka-platform-meta/issues/96#issuecomment-732237090).

My point being, I think (but I'm not entirely sure without testing it) that this new bom should not _include_ the Akka and Akka-HTTP BOMs.

Se for example, the [spring bom](https://repo1.maven.org/maven2/org/springframework/spring-framework-bom/5.3.5/spring-framework-bom-5.3.5.pom) and the [spring boot dependencies](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.4.3/spring-boot-dependencies-2.4.3.pom). Note how the `-dependencies` doesn't include the `-bom`.

2021-03-17 14:02 UTC, seglo commented on akka-platform-bom/project/Dependencies.scala
> +    // FIXME: do we support 2.11 BOM's? some projects don't publish it anymore
The example projects in the platform guide only target 2.13. If we're using them as a means to enforce compatibility maybe it would be safer to only publish this as 2.13 as well.

2021-03-17 14:05 UTC, seglo commented on akka-platform-bom/project/Dependencies.scala
> +    val AkkaCloudPlatform = "1.1.10"
We discussed versioning the platform guide documentation itself (and it's examples, I guess). We could use that version.

2021-03-17 14:14 UTC, seglo commented on akka-platform-bom/project/Dependencies.scala
> +// FIXME: wait for 3.0.0 (Alpakka), 2.1.0 (Alpakka Kafka), for Akka 2.6?
I _think_ most of Alpakka `2.0.2` will work with Akka 2.6. In some cases, like Alpakka Cassandra we've already asserted it works in projections. Alpakka Kafka `2.0.7` should work as well for the same reason. I just wasn't sure if they should be included since those releases still compile against Akka 2.5, but I'll include them anyway.

2021-03-17 14:16 UTC, seglo commented on akka-platform-bom/build.sbt
> +  )
> This new bom, OTOH, should not be called `-bom` but `-dependencies`. It _is_ formally a bom, but it lists dependencies from multiple organizations or versioning schemas. It is true that all the artifacts will (most likely) be under the Akka umbrella but, IMHO, we should add some (carefully selected) external projects. For example, I'd add Jackson artifacts on this new `akka-platform-dependencies` to lock the version better.

SGTM

2021-03-17 14:16 UTC, seglo commented on akka-platform-bom/build.sbt
> +  )
> Off-topic: TIL there's a Jackson Bom which deals with the `jacksonVersion` vs `JacksonDatabindVersion` [mess](https://github.com/akka/akka/blob/master/project/Dependencies.scala?rgh-link-date=2021-03-17T12%3A04%3A54Z#L28-L29).
> 
> See [repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom](https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/)

I'll look into adding that.

2021-03-17 14:28 UTC, seglo commented on akka-platform-bom/project/Dependencies.scala
> +  }
I missed that because it wasn't in the Lightbend build dependencies page. Maybe because it wasn't production ready for a time, but I think it is now.

2021-03-17 14:35 UTC, ignasi35 commented on akka-platform-bom/build.sbt
> +  )
> I'll look into adding that.

Wait! I'm not sure having a BOM depend on other BOMs is possible and/or valid.
Maybe we should just _know_ that Jackson BOM exists and suggest users add it.

related to https://github.com/akka/akka-platform-guide/pull/629#discussion_r595953501

2021-03-17 21:17 UTC, seglo commented on akka-platform-bom/build.sbt
> +    bomIncludeModules := Seq(akkaCoreBom, akkaHttpBom) ++ akkaManagement,
Unfortunately it does not seem that you can include nested BOMs.

2021-03-17 21:20 UTC, seglo commented on docs-source/docs/modules/how-to/examples/shopping-cart-service-cassandra-java/src/main/java/shopping/cart/ShoppingCartServer.java
> +import akka.japi.function.Function;
I was getting a maven compilation failure over this..

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project shopping-cart-service: Compilation failure                                                      
[ERROR] /home/seglo/source/akka-platform-guide/docs-source/docs/modules/how-to/examples/shopping-cart-service-cassandra-java/src/main/java/shopping/cart/ShoppingCartServer.java:[25,40] incompatible types: akka.japi.fu
nction.Function<akka.http.javadsl.model.HttpRequest,java.util.concurrent.CompletionStage<akka.http.javadsl.model.HttpResponse>> cannot be converted to akka.japi.Function<akka.http.javadsl.model.HttpRequest,java.util.c
oncurrent.CompletionStage<akka.http.javadsl.model.HttpResponse>> 
```

2021-03-17 21:38 UTC, seglo commented
I'll move this to its own repository tomorrow. Should it live in `lightbend` since it references commercial things? `lightbend/akka-platform-dependencies`

2021-03-18 07:11 UTC, patriknw commented
> I'll move this to its own repository tomorrow. Should it live in lightbend since it references commercial things? lightbend/akka-platform-dependencies

Might be more future proof to have it at lightbend if we want to include other things outside akka/akka in the same bom (or manage several different boms in that same repo).

2021-03-18 07:22 UTC, patriknw commented on akka-platform-dependencies/project/Dependencies.scala
> +    "com.typesafe.akka" %% "akka-testkit"                % Akka
double check that it's the same list as the akka-bom

2021-03-18 07:22 UTC, patriknw commented on akka-platform-dependencies/project/Dependencies.scala
> +  )
I'd like some changes to enhancements, but will take the motivation offline.

2021-03-18 07:22 UTC, patriknw commented on docs-source/docs/modules/how-to/examples/shopping-cart-service-cassandra-java/pom.xml
> +<!--        <akka-persistence-cassandra.version>1.0.5</akka-persistence-cassandra.version>-->
cleanup before merge

2021-03-18 07:22 UTC, patriknw commented on docs-source/docs/modules/how-to/examples/shopping-cart-service-cassandra-java/src/main/java/shopping/cart/ShoppingCartServer.java
> +import akka.japi.function.Function;
could it be that it's using a different Akka HTTP or gRPC version now. Good to use latest anyway.

2021-03-18 13:10 UTC, seglo commented on docs-source/docs/modules/how-to/examples/shopping-cart-service-cassandra-java/pom.xml
> +<!--        <akka-persistence-cassandra.version>1.0.5</akka-persistence-cassandra.version>-->
I'll close this PR when I move to a new repo and update the example apps later. Just testing for now.

2021-03-18 13:18 UTC, seglo commented on akka-platform-dependencies/project/Dependencies.scala
> +    "com.typesafe.akka" %% "akka-testkit"                % Akka
:+1:

2021-03-18 20:36 UTC, seglo commented
I moved the BOM to https://github.com/lightbend/akka-platform-dependencies/pull/1

I'll use this PR to update/validate the examples. We can merge it when the BOM is published.

2021-03-18 20:37 UTC, seglo commented on akka-platform-bom/project/Dependencies.scala
> +    val AkkaCloudPlatform = "1.1.10"
Reset to 1.0.0

2021-03-19 10:30 UTC, ignasi35 reviewed
A nice side effect of using BOms is that one can often shrink the list of explicit dependencies because the BOM will make sure that any transitive artifact will be loaded for the correct version. Any chance we can remove some stuff from the sample poms?

2021-03-19 10:30 UTC, ignasi35 commented on docs-source/docs/modules/how-to/examples/shopping-cart-service-java/pom.xml
> -                <version>${akka-grpc.version}</version>
Oh, wow! Controlling the grpc plugin version from the BOM is great!

2021-03-19 10:30 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/examples/00-shopping-cart-service-java/pom.xml
> -                <version>${akka-http.version}</version>
I'm still not sure the `akka-platform-dependencies` should include the `akka-bom` and the `akka-http-bom`. 🤔

The resulting XML is a lot nicer, that's is true.

2021-03-19 13:43 UTC, seglo commented on docs-source/docs/modules/microservices-tutorial/examples/00-shopping-cart-service-java/pom.xml
> -                <version>${akka-http.version}</version>
I removed the project BOM's since they can't be nested in the way I expected.

2021-03-19 13:45 UTC, seglo commented
> A nice side effect of using BOms is that one can often shrink the list of explicit dependencies because the BOM will make sure that any transitive artifact will be loaded for the correct version.

I didn't know that. I'm not sure if that's something we want to do in this case since being explicit about what dependencies are required would be informative to the user.  It is _a lot_ of dependencies though, so I'm not opposed to the idea.

2021-03-19 13:55 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/examples/00-shopping-cart-service-java/pom.xml
> -                <version>${akka-http.version}</version>
I'm not sure I understand what you mean.

I expected the `akka-platform-dependencies` to not set the Akka and Akka-HTTP versions and then my user code to depend on 3 BOMs:

```
<depMgmt>
  <akka-bom>
  <akka-http-bom>
  <akka-platform-dependencies>
</depMgmt>
```

The order of these three BOMs above is important. If my user code declared the following, the resolved artifacts would be different:

```
<depMgmt>
  <akka-platform-dependencies>
  <akka-bom>
  <akka-http-bom>
</depMgmt>
```

👆🏼 I think that in the second case whichever `akka-actor` version that's brought in transitively from any artifact in `akka-platform-dependencies` may have precedence over the version set up on `akka-bom`. Would have to test it though.

2021-03-19 14:42 UTC, seglo commented on docs-source/docs/modules/microservices-tutorial/examples/00-shopping-cart-service-java/pom.xml
> -                <version>${akka-http.version}</version>
I think `akka-platform-dependencies` should include everything, otherwise you must deal with the same version compatibility issue, but at a higher level with multiple akka project BOMs.

2021-03-19 14:55 UTC, ignasi35 commented on docs-source/docs/modules/microservices-tutorial/examples/00-shopping-cart-service-java/pom.xml
> -                <version>${akka-http.version}</version>
Hmm, you're right. It's not uncommon for a BOM to depend on other BOMS:

https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/2020.0.2/spring-cloud-dependencies-2020.0.2.pom

Let's keep it as you're doing.

2021-03-22 18:59 UTC, seglo commented on docs-source/docs/modules/microservices-tutorial/examples/00-shopping-cart-service-java/pom.xml
> -                <version>${akka-http.version}</version>
I suppose we could include the BOM's and the dependencies, but it seems redundant.

2021-03-23 16:22 UTC, ignasi35 approved these changes

2021-03-23 16:39 UTC, ignasi35 commented
`+90 −404` Nice!

2021-03-24 09:39 UTC, merged