Add Telemetry guide
akka/akka-platform-guide pull request #644
Opened 2021-03-19 23:37 UTC by marcospereira

References lightbend/cinnamon#2754.

/cc @pyoio @jtownley

2021-03-22 00:30 UTC, thothmoses commented on docs-source/docs/modules/telemetry/pages/index.adoc
> +As part of Lightbend's Intelligent Monitoring feature set, Telemetry is a suite of insight tools that provide a view into our distributed platforms' internals. This view allows developers and operati
Telemetry is a suite of tools that provide a view into your distributed platforms' internals.

2021-03-22 00:31 UTC, thothmoses commented on docs-source/docs/modules/telemetry/pages/index.adoc
> +Let's see how you can use Lightbend Telemetry in your applications.
== What's next?

Using Lightbend Telemetry in your applications.

2021-03-22 00:34 UTC, thothmoses commented
What is the predicate? Relating to the other parts of the guide what must the reader have done already?

2021-03-22 06:40 UTC, patriknw commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +<plugin>
We can include this in the shopping example projects, but commented out. Then you can pull in this as snippets. Would also be good to include `sbt` since we have that in other places for Scala.

2021-03-22 06:40 UTC, patriknw commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +```xml
same with dependencies, good to include in examples (as commented out sections)

2021-03-22 06:40 UTC, patriknw commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +cinnamon.akka.http.servers {
conf can be included in samples

2021-03-22 06:40 UTC, patriknw commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +The next step is to use Prometheus as a metrics backend.
"next" links are included automatically

2021-03-22 09:37 UTC, ignasi35 requested changes
I think Adding telemetry as a separate module is the wrong approach.

I think telemetry docs should be _sprinkled_ over the existing modules:

1. extend the `tutorial` or the `concepts` adding a page introducing the product and linking o the ref docs like in https://developer.lightbend.com/docs/akka-platform-guide/concepts/akka-stream.html
2. improve the `deployment` e.g. https://github.com/akka/akka-platform-guide/pull/642
3. move (most of) the content on this PR to the `how-to` module

Does that make sense?

2021-03-22 09:37 UTC, ignasi35 commented on docs-source/docs/antora.yml
> +- modules/telemetry/nav.adoc
Should Telemetry be a completely different module?  I got the impression the goal was to improve the `Deployment` module with the necessary bits to have telemetry on the deployed apps.

2021-03-22 09:37 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/index.adoc
> +Telemetry makes it possible to gather metrics, events, and trace information from Akka, Scala, Play, and Lagom based applications, and then store such data in {telemetry}/introduction/introduction.ht
Maybe remove `Scala` from the list of techs or add Java?
Just so it's clear that Akka-Java (or Play-Java) are also supported.

2021-03-22 13:37 UTC, marcospereira commented
Thanks for the review, @thothmoses! I will make the changes. :-)

Thanks, @patriknw. The idea is indeed to externalize the code snippets (there are some `todo` in this PR already), but I thought about doing it in a way that can be exercised by our build (instead of commented out sections). Sample can be as minimal as possible, and we can add credentials as secrets for this repo.

> I think Adding telemetry as a separate module is the wrong approach.

@ignasi35 I'm not sure about it since the sections/modules can focus on single aspects, maybe @thothmoses has some opinions here? But anyhow, I was following the decisions made in an internal document.

2021-03-22 16:38 UTC, thothmoses commented on docs-source/docs/antora.yml
> +- modules/telemetry/nav.adoc
I think it should be both a separate module and sprinkled through through the other sections as optional steps. That type of structure will allow new learners to approach the topic in isolation and in context. So, I consider the module as the first step.

2021-03-22 17:34 UTC, ignasi35 commented on docs-source/docs/antora.yml
> +- modules/telemetry/nav.adoc
But isn't `the separate module` the actual [Telemetry docs](https://developer.lightbend.com/docs/telemetry/current/home.html)?

2021-03-22 17:39 UTC, ignasi35 commented on docs-source/docs/antora.yml
> +- modules/telemetry/nav.adoc
I mean, for all other pieces of the stack the approach has been: "demo the minimum necessary to get the sample app up and running and link to ref docs".

In some occasions, in order to [keep the tutorial smaller](https://developer.lightbend.com/docs/akka-platform-guide/how-to/enable-TLS.html), we've added that minimal content as a `how-to` guide. Or maybe, we just couldn't demonstrate two libraries on a single code base, we added that on [a how-to aswell](https://developer.lightbend.com/docs/akka-platform-guide/how-to/cassandra-alternative.html). 

Then, we also have [high-level overviews](https://developer.lightbend.com/docs/akka-platform-guide/concepts/akka-persistence.html) of some pieces of the stack.

2021-03-22 18:18 UTC, thothmoses commented on docs-source/docs/antora.yml
> +- modules/telemetry/nav.adoc
To answer your first question, no. The module is supposed to be the MVP, whereas the Telemetry Docs are intended as the full kit. 
In answer to your second statement, Exactly. The goal for this stage (as I understand it) is the MVP. Then, later, we flesh out the integration. However, I do agree that at minimum, this module has to be related to the other materials in the guide. Especially outlining the required predicate actions required prior to setting up telemetry. 
I think the next natural phase is to add telemetry items into the Tutorial.

2021-03-23 16:41 UTC, ignasi35 commented on docs-source/docs/antora.yml
> +- modules/telemetry/nav.adoc
Thanks @thothmoses.

2021-03-23 16:41 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/index.adoc
> +Telemetry makes it possible to gather metrics, events, and trace information from Akka, Scala, Play, and Lagom based applications, and then store such data in {telemetry}/introduction/introduction.ht
nevermind. we can leave it as is.

2021-03-23 16:41 UTC, ignasi35 approved these changes

2021-03-24 09:19 UTC, ignasi35 commented
If #642 is merged before this, we must rebase and cross-reference or extend the contents introduced in #642 to reference the contents introduced here. 

I kept the contents on #642 to a minimum because I knew _this_  was in flight already.

2021-04-05 23:29 UTC, thothmoses commented on docs-source/docs/antora.yml
> +- modules/telemetry/nav.adoc
Actually, given the re-org of the top index page, this should reside after deployment and before how-to.

2021-04-05 23:32 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +
This should be moved to before the How-to paragraph. 
I would suggest having it say:
For those interested in adding telemetry to their deployments we advise reviewing the xref:telemetry:index.adoc[Telemetry] section.

2021-04-05 23:35 UTC, thothmoses commented
@ignasi35 @patriknw @marcospereira Query, do we have anything we can inject into the tutorial?

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +Use of lightbend Telemetry requires an account and credentials. Account options are described on the opening page of this xref::ROOT:index.adoc[].
```suggestion
Use of lightbend Telemetry requires an account and credentials. Account options are described on the opening page of this xref:ROOT:index.adoc[].
```

The syntax `xref::module:page.adoc[]` is not valid for all AsciiDoc interpreters. On My machine, the `xref::ROOT:index.adoc[]` syntax is rendered on my IDE but not by the antora-to-HTML renderer.

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +Use of lightbend Telemetry requires an account and credentials. Account options are described on the opening page of this xref::ROOT:index.adoc[].
The sentence `Account options are described on the opening page of this xref::ROOT:index.adoc[].` links to a page that has no information about Accounts. Is the link pointing to the correct page?

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +xml
```suggestion
.pom.xml:
[source,xml,indent=0]
----
```

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +=== Maven build changes
This section demonstrates the required changes for a Maven build. It should include, at least, `sbt` aswell.

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +To get started, you should configure {cinnamon-docs}/setup/setup.html[your build {tab-icon}, window="tab"] to use the Cinnamon Agent for one of the following build systems: {cinnamon-docs}/setup/cinn
```suggestion
To get started, you should configure {cinnamon-docs}/setup/setup.html[your build {tab-icon}, window="tab"] to use the Cinnamon Agent for one of the following build systems: {cinnamon-docs}/setup/cinnamon-agent-sbt.html[sbt {tab-icon}, window="tab"], {cinnamon-docs}/setup/cinnamon-agent-maven.html[Maven {tab-icon}, window="tab"], or {cinnamon-docs}/setup/cinnamon-agent-gradle.html[Gradle {tab-icon}, window="tab"].
```

I think we always use `sbt` (all lowercase).

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +The {cinnamon-docs}/setup/cinnamon-agent-maven.html[Full Telemetry Documentation {tab-icon}, window="tab"] contains full details and a complete sample.
```suggestion
The {cinnamon-docs}/setup/cinnamon-agent-maven.html[Telemetry Documentation {tab-icon}, window="tab"] contains full details and a complete sample.
```

`full ` used twice.

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +[source,xml]
```suggestion
.pom.xml:
[source,xml]
```

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +Lightbend Telemetry can capture data for {akka-http}/introduction.html[Akka HTTP and Akka gRPC {tab-icon}, window="tab"] related features. After adding the Cinnamon Agent as described above, make sur
```suggestion
Imagine we're instrumenting a simple application where we only wanted to capture metrics and traces for {akka-http}/introduction.html[Akka HTTP and Akka gRPC {tab-icon}, window="tab"]. After adding the Cinnamon Agent as described above, make sure that you add the Cinnamon Akka HTTP module dependency to your build file:
```

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +[source,conf]
```suggestion
.src/main/resources/telemetry.conf:
[source,hocon]
```

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +[source,conf]
```suggestion
.src/main/resources/telemetry.conf:
[source,hocon]
```

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/index.adoc
> +Distributed systems are complex and have many moving parts, much of which are asynchronous and run in parallel. When building complex systems, it is best to consider design in small chunks that are c
```suggestion
Distributed systems are complex and have many moving parts, much of which are asynchronous and run in parallel. When building complex systems, it is best to consider design in small chunks that are composable. Instrumenting complex systems is no different. Lightbend Telemetry breaks down into composable parts that will provide better insight into your system. This section of the Akka Platform Guide is designed to get you started with a minimum telemetry deployment.
```

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/index.adoc
> +Telemetry makes it possible to gather metrics, events, and trace information from Akka, Scala, Play, and Lagom based applications, and then store such data in {cinnamon-docs}/introduction/introductio
```suggestion
Telemetry makes it possible to gather metrics, events, and trace information from Akka, Scala, Play, and Lagom based applications, and then store such data in {cinnamon-docs}/introduction/introduction.html#backend-plugins[a metrics backend {tab-icon}, window="tab"] such as Prometheus. It collects runtime-information about your application using an agent that {cinnamon-docs}/introduction/introduction.html#instrumentations[instruments your code {tab-icon}, window="tab"] and can be configured to tailor the application needs.
```

2021-04-06 12:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/prometheus-backend.adoc
> +The following is the core Cinnamon Prometheus dependency that you will need to add to your `pom.xml`, together with the {cinnamon-docs}/plugins/prometheus/prometheus.html#http-server[HTTP server expo
We should have an sbt-equivalent for this section.

2021-04-06 15:40 UTC, rstento reviewed
Thanks for pulling this together, @marcospereira! I left a few suggestions. If you are not comfortable addressing all of them, you can put an ifdef::todo[TODO: ] note for @thothmoses to handle them later. I'm thinking especially of the introductory overview info I requested be added.

2021-04-06 16:42 UTC, thothmoses commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +Use of lightbend Telemetry requires an account and credentials. Account options are described on the opening page of this xref::ROOT:index.adoc[].
Yes, it is the correct page. The 2nd, 3rd, and 4rth, paras talk and link to the subscription options. I revise the text to indicate subscriptions.

2021-04-06 16:46 UTC, thothmoses commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +The {cinnamon-docs}/setup/cinnamon-agent-maven.html[Full Telemetry Documentation {tab-icon}, window="tab"] contains full details and a complete sample.
Actually, I think we should keep the first 'full' and change the second 'full' to 'more.'

2021-04-06 16:48 UTC, thothmoses commented on docs-source/docs/modules/telemetry/pages/index.adoc
> +Distributed systems are complex and have many moving parts, much of which are asynchronous and run in parallel. When building complex systems, it is best to consider design in small chunks that are c
Is it Telemetry itself that breaks down? Or, is it the data that Telemetry provides?

2021-04-06 17:01 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +
I'll be adding that.

2021-04-06 17:05 UTC, thothmoses commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +include::ROOT:partial$include.adoc[]
I will be adding that section info

2021-04-06 21:59 UTC, thothmoses commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +
I'll add in reference to using an IDE

2021-04-06 22:00 UTC, thothmoses commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +To get started, you should configure {cinnamon-docs}/setup/setup.html[your build {tab-icon}, window="tab"] to use the Cinnamon Agent for one of the following build systems: {cinnamon-docs}/setup/cinn
Per our discussion, I think will stay with some enhancement

2021-04-06 23:01 UTC, thothmoses commented on docs-source/docs/modules/telemetry/pages/index.adoc
> +Telemetry makes it possible to gather metrics, events, and trace information from Akka, Scala, Play, and Lagom based applications, and then store such data in {telemetry}/introduction/introduction.ht
No, I agree. Actually, I am going to pull Lagom and Play as well since they are not relevant in this doc.

2021-04-06 23:03 UTC, thothmoses commented on docs-source/docs/antora.yml
> +- modules/telemetry/nav.adoc
Ok I'll make that change

2021-04-06 23:18 UTC, thothmoses commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +include::ROOT:partial$include.adoc[]
added

2021-04-07 00:06 UTC, marcospereira commented
@rstento @thothmoses @ignasi35 

I've made some significant changes here. The guide now includes Scala/sbt, and all the code samples were extracted to a small project (inside the guide) as we do have for other places.

I'm quite not happy with the current state for the `getting-started.adoc` page because in some Scala tabs, that are more than one sub-step to conclude that step. That is because Java and Scala have different steps to configure Telemetry. I appreciate it if you can take a look and have ideas around how to better organize things.

Best.

2021-04-07 11:18 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/index.adoc
> +Distributed systems are complex and have many moving parts, much of which are asynchronous and run in parallel. When building complex systems, it is best to consider design in small chunks that are c
Ah, I see now what you meant. I think it's a bit confusing though.

Telemetry captures data. That data is not broken down by telemetry or anyone, it's already granular. OTOH, Telemetry is not a monolithic tool, instead, it's broken down into dedicated libraries that you can import and use so, instead of capturing all possible data, you can decide to capture only data produced in by a particular component on your system.

So, we could say: "telemetry is broken down into composable libraries you can cherry pick to view data from separate parts of your system.". Or something like that. Does that make sense?

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +Lightbend Telemetry can capture data for {akka-http}/introduction.html[Akka HTTP and Akka gRPC {tab-icon}, window="tab"] related features. For those interested in adding telemetry to their deployment
"Lightbend Telemetry can capture data for Akka HTTP and Akka gRPC related features"

This sentence is misleading. Lightbend Telemetry can capture data for a lot more features. If a user is not exposing an HTTP or a gRPC endpoints, they could still enable telemetry and gain insight of their system. As it is the sentence indicates only those two Akka modules are instrumented.

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/examples/telemetry-sample/project/plugins.sbt
> +addSbtPlugin("com.lightbend.cinnamon" % "sbt-cinnamon" % "2.16.0-20210319-d1d704b")
```suggestion
// TODO: replace with 2.16.0 once it's released
addSbtPlugin("com.lightbend.cinnamon" % "sbt-cinnamon" % "2.16.0-20210319-d1d704b")
```

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +Lightbend Telemetry can capture data for {akka-http}/introduction.html[Akka HTTP and Akka gRPC {tab-icon}, window="tab"] related features.
Same as above.

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +Use of lightbend Telemetry requires a subscription and credentials. A Lightbend subscription includes open source components that are distributed from the https://maven.apache.org/repository/[Maven C
```suggestion
Use of Lightbend Telemetry requires a subscription and credentials. A Lightbend subscription includes open source components that are distributed from the https://maven.apache.org/repository/[Maven Central Repository], as well as the commercial components which are distributed from a private repository. A https://www.lightbend.com/lightbend-platform-subscription[Lightbend Subscription] entitles you to use all commercial features and includes https://www.lightbend.com/lightbend-platform-subscription[support] and access to the https://academy.lightbend.com/dashboard/[Lightbend Academy].
```

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +Telemetry is also available by subscription to the Akka Cloud Platform which is via {aws-marketplace}[Amazon Web Services (AWS) {tab-icon}, window="tab"] or {gcp-marketplace}[Google Cloud Platform (G
```suggestion
Lightbend Telemetry is also available by subscription to the Akka Cloud Platform which is via {aws-marketplace}[Amazon Web Services (AWS) {tab-icon}, window="tab"] or {gcp-marketplace}[Google Cloud Platform (GCP) {tab-icon}].
```

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +----
Nice! It's great to present this as a good practice!

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +Lightbend Telemetry can capture data for {akka-http}/introduction.html[Akka HTTP and Akka gRPC {tab-icon}, window="tab"] related features. After adding the Cinnamon Agent as described above, make sur
The original write-up has the same "HTTP and gRPC" vibes I mentioned above. The suggestion I made yesterday no longer makes sense with all the added improvements.

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/getting-started.adoc
> +
Maybe we can add a final section mentioning deployment and add a cross-reference to the Akka platform operator (https://developer.lightbend.com/docs/akka-platform-guide/deployment/operator-reference.html#_reporting_metrics_to_prometheus)

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/examples/telemetry-sample/pom.xml
> +        <lightbend.cinnamon.version>2.16.0-20210319-d1d704b</lightbend.cinnamon.version>
```suggestion
        <!-- TODO: replace with 2.16.0 once it's released -->
        <lightbend.cinnamon.version>2.16.0-20210319-d1d704b</lightbend.cinnamon.version>
```

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/prometheus-backend.adoc
> +
Also add a cross-reference to https://developer.lightbend.com/docs/akka-platform-guide/deployment/operator-reference.html#_reporting_metrics_to_prometheus

2021-04-07 11:32 UTC, ignasi35 commented on docs-source/docs/modules/telemetry/pages/prometheus-backend.adoc
> +
And, while we're at it, we can also have a cross-reference back from https://developer.lightbend.com/docs/akka-platform-guide/deployment/operator-reference.html#_reporting_metrics_to_prometheus to the new content we're adding on this PR.

2021-04-07 11:33 UTC, ignasi35 commented
> I'm quite not happy with the current state for the `getting-started.adoc` page because in some Scala tabs, that are more than one sub-step to conclude that step. That is because Java and Scala have different steps to configure Telemetry. I appreciate it if you can take a look and have ideas around how to better organize things.

Not really sure how to improve that, TBH.

2021-04-07 18:10 UTC, marcospereira commented
@ignasi35 thanks! All points addressed. :-)

2021-04-08 08:50 UTC, ignasi35 commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +{cinnamon-docs}/home.html[Lightbend Telemetry {tab-icon}, window="tab"] can capture data for applications using {cinnamon-docs}/instrumentations/instrumentations.html[Akka libraries and modules{tab-i
This is great!

2021-04-08 08:51 UTC, ignasi35 approved these changes
LGTM! @thothmoses and @rstento if that works for you let's merge this!

2021-04-08 13:38 UTC, thothmoses approved these changes

2021-04-08 13:39 UTC, thothmoses commented
@marcospereira Go ahead and merge.

2021-04-08 13:42 UTC, marcospereira commented
> @marcospereira Go ahead and merge.

Auto-merge enabled. It will be merged when after a green build. :-)

2021-04-08 13:50 UTC, merged