A re-write and reorg of the top index page
akka/akka-platform-guide pull request #648
Opened 2021-03-24 00:00 UTC by thothmoses

A re-write and reorg of the top index page.

References #xxxx

2021-03-24 15:00 UTC, rstento requested changes

2021-03-24 15:11 UTC, rstento commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +This guide intends to help you get started with the array of technologies provided with the Akka Platform. Akka is a toolkit for building highly concurrent, distributed, and resilient message-driven
As a personal nit, I don't like use of the word "intends" in this context. It indicates good intentions that might not be fulfilled. :-)

Also, I think this is the place to begin introducing the different audiences and the difference between Akka Platform and Akka Cloud Platform. Maybe something like:

This guide provides information on using the Akka Platform and Akka Cloud Platform for developers, administrators, and dev/ops. The Akka Platform is a toolkit for building highly concurrent systems that are scalable, highly efficient, and resilient--using Reactive Priniciples. The Akka Cloud Platform adds tooling for deployment on Kubernetes and is available from Amazon Web Services (AWS) and (GCP).

2021-03-24 15:44 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
>  Welcome to the _Akka Platform Guide_!
Yeah, I'll kill it.

2021-03-24 16:32 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +Akka Cloud Platform helps to leverage Akka and take it to the next level. It is a subscription that enables you to quickly build and deploy cloud-native Microservices on your preferred cloud service
I'll Inject an Akka Platform description section. Truncate the lead para, and add breakout the info on ways of taking advantage.

2021-03-24 16:35 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +This guide intends to help you get started with the array of technologies provided with the Akka Platform. Akka is a toolkit for building highly concurrent, distributed, and resilient message-driven
That looks much better

2021-03-25 18:08 UTC, rstento approved these changes
Getting there! The one thing missing is that people can deploy applications built with Akka anywhere they choose. It doesn't have to be Kubernetes, and it can be on their own data centers or in the cloud. But this guide is all about deploying on Kubernetes. I'm approving so that you can get the other reviewers involved. I don't see that they've posted any comments yet.

2021-03-25 18:08 UTC, rstento commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +* Simple deployment and scaling of Kubernetes-powered Akka applications
Some of these bullets are related to each other. Suggest:

* Integrated Telemetry - integrates with popular monitoring tools and provides visibility into your distributed application
* Ops/DevOps tooling - simple deployment and scaling of Kubernetes-powered Akka applications
* Simple Integration ...
* Available through popular Cloud Marketplaces
* * Pay-as-you-go or custom pricing
* * Integrated legal agreement, purchasing and billing

2021-03-25 18:08 UTC, rstento commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +Kubernetes has become the de-facto platform for deploying in the cloud. The Cloud deployment page provides an overview of how the Kubernetes deployment works with the Akka Cloud Platform. Each cloud
I think you can remove the Kubernetes sentence. Doesn't make sense here.

2021-03-25 20:15 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +* Simple deployment and scaling of Kubernetes-powered Akka applications
Cool - tweaking

2021-03-25 20:18 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +* Zero business barriers for getting started
Make it parallel with the other two.
Get started without business barriers

2021-03-25 20:35 UTC, thothmoses commented on docs-source/docs/modules/ROOT/pages/index.adoc
> +Kubernetes has become the de-facto platform for deploying in the cloud. The Cloud deployment page provides an overview of how the Kubernetes deployment works with the Akka Cloud Platform. Each cloud
I am redacting most of this but leveraging your comment above to provide context.

2021-03-25 21:40 UTC, thothmoses commented
@patriknw If you are ok with these changes, could you merge Main into Current so that Guide is live for the Monday launch?

2021-03-26 08:26 UTC, ignasi35 approved these changes
I left a comment re the `ROOT/index.adoc` but the rest looks good to me and I'd like to push this forward.

I think we can address my comment on the `ROOT/index.adoc` in a separate PR.

2021-03-26 08:30 UTC, andreaTP approved these changes

2021-03-26 08:31 UTC, merged