AWS Quick Start concepts
akka/akka-platform-guide pull request #713
Opened 2021-05-10 18:16 UTC by seglo

A follow up for the quick start guide #706 based on feedback from @mckeeh3

2021-05-10 19:40 UTC, RayRoestenburg approved these changes

2021-05-10 20:14 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-install-quickstart.adoc
> +While the cluster is provisioning you will be informed in the terminal about which resources are in the process of being created or have been created.
```suggestion
While the cluster is provisioning you will be informed, in the terminal, about which resources are in the process of being created or have been created.
```

2021-05-10 20:15 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-install-quickstart.adoc
> +If using the the Pulumi service for state then the `pulumi up` command will include a link to "View Live" the progress of the deployment.
```suggestion
If you are using the Pulumi service for the state then the `pulumi up` command will include a link to "View Live" the progress of the deployment.
```

2021-05-10 20:16 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-install-quickstart.adoc
> +If the error can't be resolved then you can use the `pulumi destroy` command to rollback any partially deployed resources.
```suggestion
If the error can't be resolved, you can use the `pulumi destroy` command to roll back any partially deployed resources.
```

2021-05-10 20:16 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-install-quickstart.adoc
> +If the deployment is successful then all the pertinent details of the cluster will be output to the console (except for passwords).
```suggestion
If the deployment is successful, all of the pertinent details of the cluster will be output to the console (except for passwords).
```

2021-05-10 20:17 UTC, thothmoses requested changes
A few tweaks

2021-05-11 16:05 UTC, seglo commented
Don't merge this yet. Making a few more changes.

2021-05-11 16:23 UTC, thothmoses approved these changes
Excellant.

2021-05-11 19:50 UTC, merged