Quickstart installation of akka operator on GCP using Pulumi templating
akka/akka-platform-guide pull request #720
Opened 2021-05-31 05:37 UTC by debasishg

References #xxxx

2021-05-31 09:22 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: To install Akka Cloud Platform on Google Kubernetes Engine (GKE), you must have a Google account and a subscription to the {gcp-marketplace}[Akka Cloud Platform {tab-icon}, window="tab"].
Maybe add a link how to get the subscription?

2021-05-31 09:29 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: To install Akka Cloud Platform on Google Kubernetes Engine (GKE), you must have a Google account and a subscription to the {gcp-marketplace}[Akka Cloud Platform {tab-icon}, window="tab"].
@RayRoestenburg What link should we add here ?

2021-05-31 09:34 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The https://www.pulumi.com/[Pulumi {tab-icon}, window="tab"] cloud engineering (provisioning) tool to run the Playbook.
```suggestion
* The https://www.pulumi.com/[pulumi {tab-icon}, window="tab"] cloud engineering (provisioning) tool to run the Playbook.
```
(since you also did `git` and `npm`

2021-05-31 09:35 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The Kubernetes command-line tool, `kubectl`, allows you to run commands against Kubernetes clusters. Follow the instructions in the https://kubernetes.io/docs/tasks/tools/#kubectl[Kubernetes docume
```suggestion
* The Kubernetes command-line tool, `kubectl`, which allows you to run commands against Kubernetes clusters. Follow the instructions in the https://kubernetes.io/docs/tasks/tools/#kubectl[Kubernetes documentation {tab-icon}, window="tab"]  to install `kubectl`.
```

2021-05-31 09:39 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Some optional settings can be done for ready defaults. The following environment variables can be set to provide optional configurations to Pulumi Google Cloud Platform provider:
What do you mean with `ready defaults`?

2021-05-31 09:40 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +----
Are commands further on going to depend on these? since it is optional I guess not? I'm not sure if or when the reader needs these?

2021-05-31 09:45 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +By default state is managed using Pulumi's state management service (a remote service), but you can choose a https://www.pulumi.com/docs/intro/concepts/state/#backends[self-managed state backend {tab
```suggestion
State is managed by default using Pulumi's state management service (a remote service), but you can choose a https://www.pulumi.com/docs/intro/concepts/state/#backends[self-managed state backend {tab-icon}, window="tab"] if you like.
```

2021-05-31 09:48 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +pulumi stack init
The stack-name is missing in this command

2021-05-31 09:50 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +pulumi config set gcp:zone europe-west1-b
Are zone and region necessary? (if you leave it out it does not work?)

2021-05-31 09:51 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Setup the license key file path. This is required to be set in config before you run the playbook. This sets up the license key file path which will be passed to the operator deployment process. If y
```suggestion
Setup the license key file path. This is required to be set before you run the playbook. This sets up the license key file path which will be passed to the operator deployment process. If you are deploying from local environment you need to download the license file once from GCP Marketplace as per instructions in the xref:gcp-install.adoc[installation guide].
```

2021-05-31 09:53 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Setup the license key file path. This is required to be set in config before you run the playbook. This sets up the license key file path which will be passed to the operator deployment process. If y
Its not really clear how to get the license key. Can you inline the instruction?

2021-05-31 09:56 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Setup the license key file path. This is required to be set in config before you run the playbook. This sets up the license key file path which will be passed to the operator deployment process. If y
(Also it would be great to add link to marketplace page: https://console.cloud.google.com/marketplace/kubernetes/config/lightbend-public/akka-cloud-platform)

2021-05-31 09:57 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +pulumi config set akka-cloud-platform-gcp-deploy:license-file-path "/<path>/<to>/license.yaml"
Are the quotes required?

2021-05-31 10:00 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: Pulumi has a bug in tracking ready status for containiners with sidecars. In GCP implementation of akka platform operator, ubbagent (the billing agent)
```suggestion
NOTE: Pulumi has a bug in tracking ready status for containers with sidecars. In GCP implementation of akka platform operator, ubbagent (the billing agent)
```

2021-05-31 10:04 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +
maybe add output variables and configuration of playbook sections like in the AWS install quickstart?

2021-05-31 10:10 UTC, RayRoestenburg reviewed
Looks good, added some suggestions.

2021-05-31 10:18 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Some optional settings can be done for ready defaults. The following environment variables can be set to provide optional configurations to Pulumi Google Cloud Platform provider:
The next sentence explains what I mean by __ready defaults__. Setting those environment variables provide optional configurations to Pulumi GCP provider.

2021-05-31 10:19 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +----
Instead of setting environment variables, the user can use `pulumi config set` to set these values. The playbook will use these config.

2021-05-31 10:33 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The https://www.pulumi.com/[Pulumi {tab-icon}, window="tab"] cloud engineering (provisioning) tool to run the Playbook.
done ..

2021-05-31 10:33 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The Kubernetes command-line tool, `kubectl`, allows you to run commands against Kubernetes clusters. Follow the instructions in the https://kubernetes.io/docs/tasks/tools/#kubectl[Kubernetes docume
done ..

2021-05-31 10:33 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +By default state is managed using Pulumi's state management service (a remote service), but you can choose a https://www.pulumi.com/docs/intro/concepts/state/#backends[self-managed state backend {tab
done ..

2021-05-31 10:34 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +pulumi config set gcp:zone europe-west1-b
If they r not specified the values will be picked up from environment variables

2021-05-31 10:51 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Setup the license key file path. This is required to be set in config before you run the playbook. This sets up the license key file path which will be passed to the operator deployment process. If y
done ..

2021-05-31 10:52 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +pulumi config set akka-cloud-platform-gcp-deploy:license-file-path "/<path>/<to>/license.yaml"
No, unless you have some special characters in the path string. Hence just to be safe ..

2021-05-31 10:52 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: Pulumi has a bug in tracking ready status for containiners with sidecars. In GCP implementation of akka platform operator, ubbagent (the billing agent)
done

2021-05-31 11:18 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +
done

2021-06-01 19:45 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +3. Install a PostgreSQL Database Instance
```suggestion
1. Create a Google GKE cluster.
2. Install the Akka Cloud Platform Helm chart.
3. Install a PostgreSQL Database Instance.
```

2021-06-01 19:58 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The Kubernetes command-line tool, `kubectl`, which allows you to run commands against Kubernetes clusters. Follow the instructions in the https://kubernetes.io/docs/tasks/tools/#kubectl[Kubernetes
```suggestion
* The Kubernetes command-line tool, `kubectl`, allows you to run commands against Kubernetes clusters. Follow the instructions in the https://kubernetes.io/docs/tasks/tools/#kubectl[Kubernetes documentation {tab-icon}, window="tab"]  to install `kubectl`.
```

2021-06-01 19:59 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +The https://www.pulumi.com/docs/intro/cloud-providers/gcp[Pulumi Google Cloud Platform Provider {tab-icon}, window="tab"] needs to be configured with Google credentials before it can be used to creat
```suggestion
The https://www.pulumi.com/docs/intro/cloud-providers/gcp[Pulumi Google Cloud Platform Provider {tab-icon}, window="tab"] needs to be configured with Google credentials before it can be used to create resources. Ensure the following steps are complete before proceding with the creation of the cluster:
```

2021-06-01 20:00 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Setup default application credentials to interact with your Google Cloud resources. Pulumi requires this.
```suggestion
* Pulumi requires that you set up default application credentials in order to interact with your Google Cloud resources. 
```

2021-06-01 20:02 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Some optional settings can be done to provide ready defaults. The following environment variables can be set to provide optional configurations to Pulumi Google Cloud Platform provider:
```suggestion
* Some optional settings can be set up to provide ready defaults. The following environment variables can be set to provide optional configurations to the  Pulumi Google Cloud Platform provider:
```

2021-06-01 20:07 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +----
Enumerate the steps - it will make it easier to follow this section

2021-06-01 20:08 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: If you forget to set these up, the playbook will give you a gentle reminder to set the values appropriately.
'these' has an unclear antecedent.

2021-06-01 20:11 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +
I would inject a description of what you mean by playbook here. Simply because that is an overloaded term in the industry.

2021-06-01 20:13 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Later in this documentation page you can find the full list of xref:deployment:gcp-install-quickstart.adoc#output-variables[output variables].
```suggestion
Later on this page you can find the full list of xref:deployment:gcp-install-quickstart.adoc#output-variables[output variables].
```

2021-06-01 20:14 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: Pulumi has a bug in tracking ready status for containers with sidecars. In GCP implementation of akka platform operator, ubbagent (the billing agent)
```suggestion
NOTE: Pulumi has an issue with tracking ready status for containers with sidecars. In GCP implementation of the akka platform operator, ubbagent (the billing agent)
```

2021-06-01 20:16 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: Another documented bug in Pulumi is a problem in concurrency control where an operation fails with the following message. This is also documented in https://www.pulumi.com/docs/troubleshooting/
```suggestion
NOTE: Another documented issue in Pulumi is a problem in concurrency control. In this case, an operation fails with the following message. This is also documented in https://www.pulumi.com/docs/troubleshooting/#conflict[pulumi troubleshooting section {tab-icon}, window="tab"]
```

2021-06-01 20:19 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Doing a `pulumi cancel` will cancel the running update. However in some cases the update might have gone ok despite the above message. In that case `pulumi cancel` gives the following message __The U
```suggestion
Doing a `pulumi cancel` will cancel the running update. However in some cases, the update might have gone 'OK', despite the message mentioned above. In that case, `pulumi cancel` gives the following message __The Update has already completed__.
```

2021-06-01 20:20 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +To setup your local `kubectl` configuration you can obtain the Pulumi `kubeconfig` output by exporting it to a file and defining the `KUBECONFIG` environment variable:
```suggestion
To set up your local `kubectl` configuration, you can obtain the Pulumi `kubeconfig` output by exporting it to a file, and defining the `KUBECONFIG` environment variable:
```

2021-06-01 20:20 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +First you may want to set up a password for the Postgres user that you will be using. Here's how to do that for the default user `postgres`
```suggestion
First, you may want to set up a password for the Postgres user that you will be using. Here's how to do that for the default user `postgres`
```

2021-06-01 20:21 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +To print all output variables for a deployed stack you can run the following command:
```suggestion
To print all output variables for a deployed stack, you can run the following command:
```

2021-06-01 20:22 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +To output the value of only one variable use the same command and include the variable. For example, to return the clusterName.
```suggestion
To output, the value of only one variable, use the same command and include the variable. For example, to return the clusterName.
```

2021-06-01 20:24 UTC, thothmoses requested changes
See my suggestions, It's looking good.

2021-06-02 05:19 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +3. Install a PostgreSQL Database Instance
👍

2021-06-02 05:19 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The Kubernetes command-line tool, `kubectl`, which allows you to run commands against Kubernetes clusters. Follow the instructions in the https://kubernetes.io/docs/tasks/tools/#kubectl[Kubernetes
👍

2021-06-02 05:20 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +The https://www.pulumi.com/docs/intro/cloud-providers/gcp[Pulumi Google Cloud Platform Provider {tab-icon}, window="tab"] needs to be configured with Google credentials before it can be used to creat
👍

2021-06-02 05:20 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Setup default application credentials to interact with your Google Cloud resources. Pulumi requires this.
👍

2021-06-02 05:20 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +----
👍

2021-06-02 05:20 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: If you forget to set these up, the playbook will give you a gentle reminder to set the values appropriately.
Made the context explicit

2021-06-02 05:20 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +
👍

2021-06-02 05:21 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: Pulumi has a bug in tracking ready status for containers with sidecars. In GCP implementation of akka platform operator, ubbagent (the billing agent)
👍

2021-06-02 05:21 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: Another documented bug in Pulumi is a problem in concurrency control where an operation fails with the following message. This is also documented in https://www.pulumi.com/docs/troubleshooting/
👍

2021-06-02 05:21 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Doing a `pulumi cancel` will cancel the running update. However in some cases the update might have gone ok despite the above message. In that case `pulumi cancel` gives the following message __The U
👍

2021-06-02 05:21 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +To setup your local `kubectl` configuration you can obtain the Pulumi `kubeconfig` output by exporting it to a file and defining the `KUBECONFIG` environment variable:
👍

2021-06-02 05:21 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +First you may want to set up a password for the Postgres user that you will be using. Here's how to do that for the default user `postgres`
👍

2021-06-02 05:21 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +To print all output variables for a deployed stack you can run the following command:
👍

2021-06-02 05:22 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +To output the value of only one variable use the same command and include the variable. For example, to return the clusterName.
👍

2021-06-02 05:22 UTC, debasishg commented
@thothmoses I have added all the feedbacks based on your review. Please take a look ..

2021-06-02 14:00 UTC, marcospereira reviewed
This is looking great, @debasishg! Some minor suggestions and questions.

2021-06-02 14:00 UTC, marcospereira commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +| No
What is the default then?

2021-06-02 14:22 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The Kubernetes command-line tool, `kubectl`, allows you to run commands against Kubernetes clusters. Follow the instructions in the https://kubernetes.io/docs/tasks/tools/#kubectl[Kubernetes docume
Um,  no. Aiding the 'which' requires that you add a subordinate clause

2021-06-02 14:23 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The Kubernetes command-line tool, `kubectl`, allows you to run commands against Kubernetes clusters. Follow the instructions in the https://kubernetes.io/docs/tasks/tools/#kubectl[Kubernetes docume
@marcospereira do you mean we need to add the entire paragraph to the AWS section?

2021-06-03 04:25 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +A new installation will take approximately  _20 minutes_ and the following components will be provisioned:
@marcospereira It installs less stuff .. no Kafka :-)

2021-06-03 04:33 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +== Quick Start with Pulumi Playbook
I followed the AWS doc template here.

2021-06-03 04:44 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +| No
There is no default here. It can be optionally set through environment variables or `pulumi config`, otherwise it continues with some provider default, which we don't set

2021-06-03 04:44 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Doing a `pulumi cancel` will cancel the running update. However in some cases the update might have gone __'OK'__ despite the message mentioned above. In that case, `pulumi cancel` gives the followin
👍

2021-06-03 04:44 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Just run `pulumi up` again which is basically a noop but the stack gets updated fully.
👍

2021-06-03 04:44 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: Pulumi has an issue with tracking ready status for containers with sidecars. In GCP implementation of the akka platform operator, ubbagent (the billing agent)
👍

2021-06-03 04:44 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +After executing `pulumi up` you will see something like the following:
👍

2021-06-03 04:44 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +When this occurs and you can correct the issue yourself then rerun `pulumi up` to resume updating where you left off.
👍

2021-06-03 04:45 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +If you are using the Pulumi service for the state then the `pulumi up` command will include a link to "View Live" the progress of the deployment.
👍

2021-06-03 04:45 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Preview and provision the playbook.
👍

2021-06-03 04:45 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +In almost all cases resources will start with a prefix `acp-<STACK NAME>`, where `acp` stands for "Akka Cloud Platform" and `<STACK NAME>` is the name you chose for the Pulumi stack.
👍

2021-06-03 04:46 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Install the https://cloud.google.com/sdk/install[Google Cloud SDK {tab-icon}, window="tab"] and then https://cloud.google.com/sdk/docs/authorizing#authorizing_with_a_user_account[authorize access w
Added this as a prerequisite in the prerequisites section.

2021-06-03 04:46 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +== Verify Prerequisites
👍

2021-06-03 04:46 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Before installation, you must subscribe to the {gcp-marketplace}[Akka Cloud Platform {tab-icon}, window="tab"] on GCP Marketplace by clicking the Subscribe button on the product page and accepting th
👍

2021-06-03 04:55 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> + +   pulumi:pulumi:Stack                                                  akka-cloud-platform-gcp-deploy-<STACK NAME>                                                 create
@marcospereira Resources' names like cluster name (`acp-dev-gke`) and service account (`acp-dev-sa`) starts with `acp-`, the Stack name is different. Do I need to make any change here ?

2021-06-03 04:57 UTC, debasishg commented
@marcospereira Added review feedbacks ..

2021-06-03 14:24 UTC, marcospereira commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> + +   pulumi:pulumi:Stack                                                  akka-cloud-platform-gcp-deploy-<STACK NAME>                                                 create
I don't think so. I was mixing different things. Sorry.

2021-06-03 14:26 UTC, marcospereira commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The Kubernetes command-line tool, `kubectl`, allows you to run commands against Kubernetes clusters. Follow the instructions in the https://kubernetes.io/docs/tasks/tools/#kubectl[Kubernetes docume
@thothmoses, the paragraph is already there, but if we need to add the `which` here, it makes sense to add it there too. I'm not an English native speaker, so I will defer to you if this is necessary or not.

2021-06-03 14:36 UTC, marcospereira approved these changes
LGTM. Thanks, @debasishg.

@RayRoestenburg @thothmoses if you are happy with it, let's merge it then. :-)

2021-06-03 15:05 UTC, thothmoses approved these changes

2021-06-03 15:44 UTC, rstento requested changes
Whew, @debasishg, it was obviously a lot of work to capture all this, good job! 

I do agree with the comment that it would be better to first explain the Pulomi concepts and then give a general overview of the steps required before even running the playbook. It is very easy to get lost when it is such a multi-step process.

Note that if you do include a code block or sentences of explanation after a numbered step, you need to add a + sign to make it indent correctly:

. This is a step
+
[source, text]
----
This is a code block
----

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +1. Create a Google GKE cluster.
These don't correspond with the steps that follow. To be paralell with the lead-in sentence, they should be regular bullets:

* A Google GKE cluster
* The Akka Cloud Platform Helm chart
* A PostgreSQL Database Instance

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
>  In addition, in order to operate the cluster, you need to setup:
s/be "set up"

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Pulumi requires that you setup default application credentials in order to interact with your Google Cloud resources. Pulumi requires this.
"set up" instead of setup. And the "Pulumi requires this." is unnecessary, it just repeats what is said in the previous paragraph.

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Some optional settings can be set up to provide ready defaults. The following environment variables can be set to provide optional configurations to the Pulumi Google Cloud Platform provider:
```suggestion
* You can set the following environment variables to provide default options to the Pulumi Google Cloud Platform provider:
```

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +The fastest way to get started with Akka Cloud Platform on GCP is to run the Akka Cloud Platform Deployment Pulumi playbook, which contains a bunch of instructions that plays like a book when run and
```suggestion
The fastest way to get started with Akka Cloud Platform on GCP is to run the Akka Cloud Platform Deployment Pulumi playbook. The playbook contains a set of instructions that will provision the cluster and all the appropriate artifacts.
```

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Here are the steps to follow to have your playbook up 'n running:
and instead of 'n?

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Download and install the https://www.pulumi.com/docs/get-started/install/[Pulumi {tab-icon}, window="tab"] cloud engineering (provisioning) tool for your platform.
This is different from the playbook? It's a bit confusing.

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Download (clone) the https://github.com/lightbend/akka-cloud-platform-deploy[Akka Cloud Platform Deployment Pulumi Playbook {tab-icon}, window="tab"] with https://git-scm.com/book/en/v2/Getting-Sta
is (clone) necessary?

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The same repository contains the scripts for AWS and GCP deployment. Navigate to the `gcp` folder.
```suggestion
* The repository contains scripts for both AWS and GCP deployment. Navigate to the `gcp` folder.
```

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
>  A stack is an instance of the deployed Pulumi playbook and its associated state.
This too seems like concepts that s/be introduced before the steps.

And, the definition of stack doesn't jibe with how a playbook is described above. Maybe:

A stack is the cluster and its artifacts with associated state, as provisioned by a Pulumi playbook.

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Choose Google Project Id, zone and region to use:
Choose "the"

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Setup the license key file path. This is required to be set before you run the playbook. This sets up the license key file path which will be passed to the operator deployment process. If you are d
```suggestion
* Set up the license key file path. This is required before you run the playbook. It will be passed to the operator deployment process. If you are deploying from your local environment you need to download the license file once from GCP Marketplace following the instructions in the xref:gcp-install.adoc[installation guide]. In the {gcp-marketplace}[Akka Cloud Platform {tab-icon}, window="tab"] for GCP page, click on __Configure__ and then go to the tab __Deploy via command line__ and click on __Generate license key__. A `license.yaml` will be generated on your local system.
```

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Setup the version of the operator.
Set instead of set up?

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: If you forget to set the license key file path and operator version up, the playbook will give you a gentle reminder to set the values appropriately.
Is this really necessary? If they follow our steps, they will never see the reminder and if they don't and see the reminder, we don't really need to tell them about it, do we?

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
>  In almost all cases resources will start with a prefix `acp-<STACK NAME>`, where `acp` stands for "Akka Cloud Platform" and `<STACK NAME>` is the name you chose for the Pulumi stack.
```suggestion
In almost all cases, resources will start with a prefix `acp-<STACK NAME>`, where `acp` stands for "Akka Cloud Platform" and `<STACK NAME>` is the name you chose for the Pulumi stack.
```

2021-06-03 15:44 UTC, rstento commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Doing a `pulumi cancel` will cancel the running update. However in some cases the update might have gone __'OK'__ despite the message mentioned above. In that case, `pulumi cancel` gives the followin
```suggestion
Entering `pulumi cancel` will cancel the running update. However, in some cases, the update might have a status of  'OK', contrary to the message mentioned above. In that case, `pulumi cancel` gives the following message `The Update has already completed`.
```

2021-06-03 16:31 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Pulumi requires that you setup default application credentials in order to interact with your Google Cloud resources. Pulumi requires this.
```suggestion
*  You are required to set up default application credentials in order to interact with your Google Cloud resources. Pulumi requires this.
```

2021-06-03 16:38 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Some optional settings can be set up to provide ready defaults. The following environment variables can be set to provide optional configurations to the Pulumi Google Cloud Platform provider:
I think the suggestion is may be truncated.
```suggestion
* Optionally, you can set the following environment variables to provide preset default configurations for the Pulumi Google Cloud Platform provider:
```

2021-06-03 16:43 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +The fastest way to get started with Akka Cloud Platform on GCP is to run the Akka Cloud Platform Deployment Pulumi playbook, which contains a bunch of instructions that plays like a book when run and
I think that running the playbook has to be explicit.

```suggestion
The fastest way to get started with Akka Cloud Platform on GCP is to run the Akka Cloud Platform Deployment Pulumi playbook. The playbook contains a set of instructions that, when run, will provision the cluster and all the appropriate artifacts.
```

2021-06-03 16:46 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: If you forget to set the license key file path and operator version up, the playbook will give you a gentle reminder to set the values appropriately.
It is nice to have as an assurance if you are reading through the doc separate from when actually working through the steps.

2021-06-04 04:38 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Download and install the https://www.pulumi.com/docs/get-started/install/[Pulumi {tab-icon}, window="tab"] cloud engineering (provisioning) tool for your platform.
It's different from the playbook. It's the engine which will run the playbook

2021-06-04 04:39 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Download (clone) the https://github.com/lightbend/akka-cloud-platform-deploy[Akka Cloud Platform Deployment Pulumi Playbook {tab-icon}, window="tab"] with https://git-scm.com/book/en/v2/Getting-Sta
Yes, the user needs to _clone_ the git repo to download the playbook

2021-06-04 04:51 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +1. Create a Google GKE cluster.
👍

2021-06-04 04:51 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
>  In addition, in order to operate the cluster, you need to setup:
👍

2021-06-04 04:51 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Pulumi requires that you setup default application credentials in order to interact with your Google Cloud resources. Pulumi requires this.
👍

2021-06-04 04:51 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Some optional settings can be set up to provide ready defaults. The following environment variables can be set to provide optional configurations to the Pulumi Google Cloud Platform provider:
👍

2021-06-04 04:52 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +The fastest way to get started with Akka Cloud Platform on GCP is to run the Akka Cloud Platform Deployment Pulumi playbook, which contains a bunch of instructions that plays like a book when run and
👍

2021-06-04 04:52 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Here are the steps to follow to have your playbook up 'n running:
👍

2021-06-04 04:52 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* The same repository contains the scripts for AWS and GCP deployment. Navigate to the `gcp` folder.
👍

2021-06-04 04:52 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
>  A stack is an instance of the deployed Pulumi playbook and its associated state.
👍

2021-06-04 04:52 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Choose Google Project Id, zone and region to use:
👍

2021-06-04 04:53 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Setup the license key file path. This is required to be set before you run the playbook. This sets up the license key file path which will be passed to the operator deployment process. If you are d
👍

2021-06-04 04:53 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +* Setup the version of the operator.
👍

2021-06-04 04:53 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
>  In almost all cases resources will start with a prefix `acp-<STACK NAME>`, where `acp` stands for "Akka Cloud Platform" and `<STACK NAME>` is the name you chose for the Pulumi stack.
👍

2021-06-04 04:53 UTC, debasishg commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +Doing a `pulumi cancel` will cancel the running update. However in some cases the update might have gone __'OK'__ despite the message mentioned above. In that case, `pulumi cancel` gives the followin
👍

2021-06-04 04:54 UTC, debasishg commented
@rstento @thothmoses I have incorporated all suggestions that you made. Please take a look

2021-06-04 15:25 UTC, rstento approved these changes
Thanks @debasishg, LGTM!

2021-06-07 05:01 UTC, merged