Document custom-kubernetes usage
akka/akka-platform-guide pull request #733
Opened 2021-07-08 15:41 UTC by ignasi35

Docs for https://github.com/lightbend/akka-platform-operator/pull/576

2021-07-12 09:55 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +Next, make sure you have the commercial Lightbend charts:
```suggestion
Next, make sure you have the akka-operator-helm chart:
```
The charts are not really 'commercial'

2021-07-12 10:10 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +{lightbend-developer-docs}/introduction/getting-started/subscription-and-credentials.html[Lightbend Subscription {tab-icon}, window="tab"] have access to the Akka Cloud Platform operator to run on th
We should document our versions policy for Kubernetes. The doc had some reference to version-skew-policy, likely we want to be even more restrictive than the Kubernetes policy: https://docs.google.com/document/d/11kDVXyi3qn3xnpUI3Az1zm-VfPPS9iriOp3IkreyjC4/edit#

The doc is currently out of date, but I think this part might still valid, let's check with @jtownley .

2021-07-12 10:17 UTC, RayRoestenburg commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +The Akka Cloud Platform operator will not be in charge of creating the necessary `Ingress` instances to handle external traffic into your `AkkaMicroservice` (unlike the deployment on xref:aws-ingress
Maybe something like this:
```suggestion
xref:gcp-install.adoc[Deploying with Google Cloud Platform (GCP)] and xref:aws-index.adoc[Deploying with Amazon Web Services (AWS)] integrate with cloud provider specific features, like databases, message brokers and ingress.

When you install the the Akka Cloud Platform operator on a custom Kubernetes cluster, it will not be in charge of creating the necessary `Ingress` instances to handle external traffic into your `AkkaMicroservice` (unlike the deployment on xref:aws-ingress.adoc[AWS] or xref:gcp-ingress.adoc[GCP] where the operator can fine tune all the necessary resources). The `Ingress` resources require cloud-specific tuning, you will need to refer to your kubernetes provider (e.g. minikube docs, Azure docs, etc...) in order to create an Ingress that can handle TLS-enabled, HTTP/2 traffic to serve gRPC externally.
```

2021-07-12 10:21 UTC, RayRoestenburg reviewed
Looks good, some suggestions. I remember James saying something about CPU / licensing, that might be needed in the docs, or refer to other docs. It's also important to make sure users understand we do not support all kubernetes flavours and versions under the sun, please check with James what the official text on that should be (can also be done as a separate PR IMHO)

2021-07-12 13:02 UTC, jtownley commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +{lightbend-developer-docs}/introduction/getting-started/subscription-and-credentials.html[Lightbend Subscription {tab-icon}, window="tab"] have access to the Akka Cloud Platform operator to run on th
I agree we should mention this. @Ray Why more restrictive? What are you thinking?

2021-07-12 22:59 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +Make sure you read the xref:cloud-deployment.adoc[] and xref:deploy.adoc[] before proceeding to understand the basic deployment architecture and workflow.
```suggestion
In order to best understand the basic deployment architecture and workflow, make sure you read the xref:cloud-deployment.adoc[] and xref:deploy.adoc[] before proceeding further.
```

2021-07-12 23:02 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +Make sure your `kubectl` context points to your local Kubernetes cluster (for example, {minikube}[minikube {tab-icon}, window="tab"]), or an external Kubernetes cluster (e.g. in https://docs.microsof
```suggestion
Verify that your `kubectl` context points to your local Kubernetes cluster (for example, {minikube}[minikube {tab-icon}, window="tab"]), or an external Kubernetes cluster (as illustrated in https://docs.microsoft.com/en-ca/azure/aks/kubernetes-walkthrough[Azure {tab-icon}, window="tab"]).
```
Too many 'make sure's'

2021-07-12 23:03 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +Deploying the Akka Cloud Platform operator xref:gcp-install.adoc[with Google Cloud Platform (GCP)] or xref:aws-index.adoc[with Amazon Web Services (AWS)] enables integration with databases, message b
```suggestion
Deploying the Akka Cloud Platform operator xref:gcp-install.adoc[with Google Cloud Platform (GCP)] or xref:aws-index.adoc[with Amazon Web Services (AWS)] enables integration with databases, message brokers, and ingress specific to GCP or AWS.
```

2021-07-12 23:09 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +When you install the the Akka Cloud Platform operator on a custom Kubernetes cluster, it will not be in charge of creating the necessary `Ingress` instances to handle external traffic into your `Akka
```suggestion
When you install the Akka Cloud Platform operator on a custom Kubernetes cluster, it will not be in charge of creating the `Ingress` instances required to handle external traffic into your `AkkaMicroservice`. This is unlike the deployment on xref:aws-ingress.adoc[AWS] or xref:gcp-ingress.adoc[GCP], where the operator can fine-tune all the necessary resources. The `Ingress` resources require cloud-specific tuning. You will need to refer to your Kubernetes provider (such as minikube docs, Azure docs) to create an Ingress that can handle TLS-enabled, HTTP/2 traffic to serve gRPC externally.
```

2021-07-12 23:10 UTC, thothmoses requested changes
A few tweaks.

2021-07-13 07:59 UTC, ignasi35 commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +Make sure your `kubectl` context points to your local Kubernetes cluster (for example, {minikube}[minikube {tab-icon}, window="tab"]), or an external Kubernetes cluster (e.g. in https://docs.microsof
Thanks @thothmoses :-)

2021-07-13 08:04 UTC, ignasi35 commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +{lightbend-developer-docs}/introduction/getting-started/subscription-and-credentials.html[Lightbend Subscription {tab-icon}, window="tab"] have access to the Akka Cloud Platform operator to run on th
I'm not familiar enough with Kubernetes versions and the requirements for the operator to work as expected. I think we could specify that Kubernetes 1.19 is required and be a bit vague so the write-up of supported Kubernetes versions is easier to maintain.

Eventually, when we're swamped in support cases we'll have a wider testbed and can better document the supported versions or the minimum k8s version for each operator release.

2021-07-13 08:28 UTC, ignasi35 commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +{lightbend-developer-docs}/introduction/getting-started/subscription-and-credentials.html[Lightbend Subscription {tab-icon}, window="tab"] have access to the Akka Cloud Platform operator to run on th
In any case, we don't specify a Kubernetes version anywhere else on this guide. IIRC, GKE supports specifying the k8s version to use when creating a cluster and we don't set a minimum version.

Currently the only reference to a k8s version is on a link to some docs (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#event-v1-core) but those docs are identical in 1.18.


We should have a compatibility matrix for the operator/k8s/cloud/metrics-server combinations but I'd rather do it on a separate PR.

2021-07-13 19:09 UTC, marcospereira commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +{lightbend-developer-docs}/introduction/getting-started/subscription-and-credentials.html[Lightbend Subscription {tab-icon}, window="tab"] have access to the Akka Cloud Platform operator to run on th
I guess that we want to include support for Kubernetes versions that are not yet supported by GKE and EKS, but do we want to drop support for versions that they still support? 

I'm asking because following the Kubernetes version-skew-policy may not be the best option, considering how cloud providers pile up their own policies on top of that. For example, this is what [GKE docs says about version support](https://cloud.google.com/kubernetes-engine/versioning#stable):

> Google provides a total of **14 months of support** for each GKE minor version once the version has been made available in the **Regular** channel.

And here is the release schedule:

https://cloud.google.com/kubernetes-engine/docs/release-schedule

What we have there for K8s 1.19 is:

| Kubernetes version | Kubernetes release date | Rapid      | Regular    | Stable  |
|:-------------------|:------------------------|:-----------|:-----------|:--------|
| 1.19               | 2020-08-26              | 2021-01-25 | 2021-04-18 | 2021-06 |

It took ~5 months from K8s release to **Rapid** channel, then ~3 months from **Rapid** to **Regular**. From **Regular** to EOL, it will take 14 months. In total, from OSS release to EOL in GKE, it will take ~21 months.

Numbers for EKS are similar: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar.

With a similar policy (from the FAQ in the link above):

> Q: How long is a Kubernetes version supported by Amazon EKS?
>
> A: A Kubernetes version is fully supported for **14 months after first being available on Amazon EKS**. This is true even if upstream Kubernetes is no longer supporting a version available on Amazon EKS.

I'm not sure what would be the best option, here, but a suggestion would be to support the union of:

1. K8s OSS supported versions
2. GKE versions in the *Regular* channel
3. Some subset of EKS supported versions?

WDYT?

2021-07-14 06:57 UTC, ignasi35 commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +{lightbend-developer-docs}/introduction/getting-started/subscription-and-credentials.html[Lightbend Subscription {tab-icon}, window="tab"] have access to the Akka Cloud Platform operator to run on th
I think we can move this to a separate PR. As you surfaced, the issue is tricky and requires a bit more writeup and explanation than a simple paragraph.

2021-07-14 07:10 UTC, ignasi35 commented on docs-source/docs/modules/deployment/pages/bring-your-kubernetes-cluster.adoc
> +{lightbend-developer-docs}/introduction/getting-started/subscription-and-credentials.html[Lightbend Subscription {tab-icon}, window="tab"] have access to the Akka Cloud Platform operator to run on th
Raised #737

2021-07-15 13:56 UTC, RayRoestenburg approved these changes

2021-07-15 17:01 UTC, thothmoses approved these changes
LGTM

2021-07-15 20:39 UTC, merged