Pulumi: document how to install Telemetry backends
akka/akka-platform-guide pull request #742
Opened 2021-07-15 20:46 UTC by marcospereira

- aws: Update quickstart guide to include new Pulumi changes
- gcp: Update quickstart guide to include new Pulumi changes

Reference: lightbend/akka-cloud-platform-deploy#12.

2021-07-15 23:25 UTC, ygree commented on docs-source/docs/modules/deployment/pages/aws-install-quickstart.adoc
> +| Whether to install the Kubernetes metrics server.
We should probably explain a bit why metrics-server is needed.

2021-07-15 23:27 UTC, ygree commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +A new installation will take approximately  _20 minutes_, and by default, the following components will be provisioned:
Maybe `components will be provisioned` -> `steps will be executed`

2021-07-15 23:29 UTC, ygree commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +[#connect-grafana]
We should probably extract this fragment and include it in GCP and AWS instructions.

2021-07-15 23:31 UTC, ygree requested changes
LGTM just made a couple suggestions

2021-07-16 00:05 UTC, marcospereira commented on docs-source/docs/modules/deployment/pages/aws-install-quickstart.adoc
> +| Whether to install the Kubernetes metrics server.
Now that you mentioned that, we should not have an option to disable installing `metrics-server` since it is a runtime requirement for `akka-platform-operator`.

See https://github.com/lightbend/akka-cloud-platform-deploy/pull/16.

2021-07-16 00:06 UTC, marcospereira commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +A new installation will take approximately  _20 minutes_, and by default, the following components will be provisioned:
Done here and in the AWS version too. :-)

2021-07-16 00:06 UTC, marcospereira commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +[#connect-grafana]
Done!

2021-07-16 00:24 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-install-quickstart.adoc
> +7. Setup an Amazon Aurora Relational Database Service (RDS) cluster
```suggestion
6. Set up an Amazon Managed Streaming for Apache Kafka (MSK) cluster
7. Set up an Amazon Aurora Relational Database Service (RDS) cluster
```

2021-07-16 00:25 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/aws-install-quickstart.adoc
> +NOTE: We recommend Node 14 or later.
Is this a recommendation or a requirement?

2021-07-16 00:26 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +5. Setup a PostgreSQL Database Instance
```suggestion
5. Set up a PostgreSQL Database Instance
```

2021-07-16 00:27 UTC, thothmoses commented on docs-source/docs/modules/deployment/pages/gcp-install-quickstart.adoc
> +NOTE: Another documented issue in Pulumi is a problem in concurrency control. In this case, an operation fails with the following message. This is also documented in https://www.pulumi.com/docs/troub
```suggestion
NOTE: Another documented issue in Pulumi is within concurrency control. In this case, an operation fails with the following message. This is also documented in https://www.pulumi.com/docs/troubleshooting/#conflict[Pulumi troubleshooting section {tab-icon}, window="tab"]
```

2021-07-16 00:28 UTC, thothmoses approved these changes
Looking good - I suggested a few tweaks

2021-07-16 13:47 UTC, ygree approved these changes
LGTM

2021-07-16 13:47 UTC, merged

2021-07-16 14:16 UTC, marcospereira commented on docs-source/docs/modules/deployment/pages/aws-install-quickstart.adoc
> +NOTE: We recommend Node 14 or later.
It is a recommendation, I'm pretty sure it works with Node 10, for example. But this is the version I'm using while developing and testing (including in our CI).

2021-07-16 14:21 UTC, marcospereira commented
@thothmoses, the pull request was merged before I had a chance to accept your suggestions. Here is a new pull request to fix those issues: https://github.com/akka/akka-platform-guide/pull/743.